// Hand-drawn 12×12 pixel sprites. Each row is 12 characters; "." is empty and
// every other character is a colour from PALETTE. To add an icon, draw it here.
export const PALETTE: Record<string, string> = {
  k: "#2b2119",
  w: "#ffffff",
  c: "#f4efe6",
  r: "#d7263d",
  n: "#e8a0a0",
  o: "#f28c28",
  y: "#ffd23f",
  t: "#d9b45a",
  b: "#8b5a2b",
  d: "#5e3b1c",
  g: "#3fa34d",
  G: "#2d6e35",
  l: "#9fd356",
  s: "#a3a9ae",
  S: "#5f656b",
  u: "#4a90e2",
  U: "#1e4f9c",
  p: "#f1c7a0",
  m: "#b5651d",
  v: "#8e5cc2",
};

export const SPRITES = {
  flame: [
    ".....r......",
    ".....rr.....",
    "....ror.....",
    "...roor..r..",
    "...rooor.r..",
    "..rooyoorr..",
    "..royyyoor..",
    "..royyyyor..",
    "..royyyyor..",
    "...ryyyyr...",
    "....rrrr....",
    "............",
  ],
  campfire: [
    ".....r......",
    "....ror.....",
    "...rooor....",
    "...royor.r..",
    "..royyyor...",
    "..royyyor...",
    "...ryyyr....",
    ".d..rrr..d..",
    "..dd...dd...",
    "...ddddd....",
    "..dd...dd...",
    ".d.......d..",
  ],
  hut: [
    ".....kk.....",
    "....kttk....",
    "...kttttk...",
    "..kttttttk..",
    ".kttttttttk.",
    "kttttttttttk",
    ".kbbbbbbbbk.",
    ".kbbbddbbbk.",
    ".kbbbddbbbk.",
    ".kbbbddbbbk.",
    ".kkkkkkkkkk.",
    "............",
  ],
  basket: [
    "............",
    "...r..r.....",
    "..rrr.rr.r..",
    "...kkkkkkr..",
    "..k......k..",
    ".kkkkkkkkkk.",
    ".kttttttttk.",
    ".ktdtdtdtdk.",
    ".kttttttttk.",
    ".ktdtdtdtdk.",
    "..kttttttk..",
    "...kkkkkk...",
  ],
  axe: [
    "............",
    "..sss.......",
    ".sssss......",
    ".ssssSd.....",
    "..sssSdd....",
    "....Sddd....",
    ".....ddd....",
    "......ddd...",
    ".......ddd..",
    "........ddd.",
    ".........dd.",
    "............",
  ],
  wheat: [
    "...y...y..y.",
    "..yy..yy.yy.",
    "...y...y..y.",
    "..yy..yy.yy.",
    "...y...y..y.",
    "..yy..yy.yy.",
    "...g...g..g.",
    "...g...g..g.",
    "...g...g..g.",
    ".bbbbbbbbbbb",
    ".ddddddddddd",
    "............",
  ],
  shield: [
    "..kkkkkkkk..",
    ".krrrrrrrrk.",
    ".krrrrwrrrk.",
    ".krrrwwwrrk.",
    ".krrrrwrrrk.",
    ".krrrrwrrrk.",
    "..krrrrrrk..",
    "..krrrrrrk..",
    "...krrrrk...",
    "....krrk....",
    ".....kk.....",
    "............",
  ],
  sword: [
    "..........ss",
    ".........sws",
    "........sws.",
    ".......sws..",
    "......sws...",
    ".....sws....",
    "..y.sws.....",
    "...yws......",
    "...dy.......",
    "..dd.y......",
    ".dd.........",
    "kd..........",
  ],
  fish: [
    "............",
    "............",
    "...uuuu.....",
    "..uuuuuu..u.",
    ".uukwuuuuuu.",
    ".uuuuuuuuu..",
    ".UuuuuuuuuU.",
    "..UuuuuU..U.",
    "...UUUU.....",
    "............",
    "............",
    "............",
  ],
  pickaxe: [
    "...sssss....",
    "..sS...Ss...",
    ".sS..d..Ss..",
    ".s...d...s..",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    "............",
  ],
  rock: [
    "............",
    "............",
    "....ssss....",
    "..sssssss...",
    ".sssswsssS..",
    ".sssssssSS..",
    "ssssssSSSSS.",
    "sssssSSSSSS.",
    ".SSSSSSSSS..",
    "............",
    "............",
    "............",
  ],
  feather: [
    "..........cc",
    ".........ccc",
    "........cckc",
    ".......cckc.",
    "......cckc..",
    ".....cckc...",
    "....cckc....",
    "...cckc.....",
    "..cckc......",
    "..ckc.......",
    ".kk.........",
    "k...........",
  ],
  herb: [
    "............",
    "....gggg....",
    "....glgg....",
    "....gggg....",
    ".gggggggggg.",
    ".glllgggggg.",
    ".gggggggggg.",
    ".gggggggggg.",
    "....gggg....",
    "....gggg....",
    "....gggg....",
    "............",
  ],
  meat: [
    "............",
    "...nnnnn....",
    "..nrrrrrn...",
    ".nrrrrrrrn..",
    ".nrrrrrrrn..",
    ".nrrrrrrn...",
    "..nrrrrn....",
    "....ncc.....",
    ".....cc.....",
    "....c..c....",
    "....cc.cc...",
    "............",
  ],
  log: [
    "............",
    "............",
    "............",
    "..bbbbbbbbt.",
    ".bbbbbbbbttt",
    ".ddddddddtdt",
    ".bbbbbbbbttt",
    "..ddddddddt.",
    "............",
    "............",
    "............",
    "............",
  ],
  bulb: [
    "....yyyy....",
    "...yyyyyy...",
    "..yywyyyyy..",
    "..ywyyyyyy..",
    "..yyyyyyyy..",
    "...yyyyyy...",
    "....yyyy....",
    "....ssss....",
    "....SSSS....",
    "....ssss....",
    ".....SS.....",
    "............",
  ],
  coin: [
    "............",
    "...yyyyyy...",
    "..yyooooyy..",
    ".yyoyyyyoyy.",
    ".yoyyoyyyoy.",
    ".yoyyoyyyoy.",
    ".yoyyoyyyoy.",
    ".yyoyyyyoyy.",
    "..yyooooyy..",
    "...yyyyyy...",
    "............",
    "............",
  ],
  person: [
    "....kkkk....",
    "...kddddk...",
    "...kppppk...",
    "...kppppk...",
    "....kkkk....",
    "..kkmmmmkk..",
    ".kmmmmmmmmk.",
    ".kmkmmmmkmk.",
    ".kpkmmmmkpk.",
    "..kkmmmmkk..",
    "...kdkkdk...",
    "...kk..kk...",
  ],
  sheep: [
    "............",
    "...kkkkk....",
    "..kwwcwwk...",
    ".kwwwwwwwkkk",
    "kwwcwwwcwkwk",
    "kwwwwwwwwkkk",
    ".kwwwwwwwk..",
    "..kkkkkkk...",
    "..k.k..k.k..",
    "..k.k..k.k..",
    "............",
    "............",
  ],
  sapling: [
    "............",
    ".....gg.....",
    "....gllg....",
    "...glllg.g..",
    "....gllgglg.",
    ".g...bgglg..",
    "glg..b.gg...",
    ".gg..b......",
    "..g..b......",
    "..gg.b......",
    "...ddbdd....",
    "..dddddddd..",
  ],
  stump: [
    "............",
    "............",
    "............",
    "............",
    "...tttttt...",
    "..tbbbbbbt..",
    "..tbttttbt..",
    "..tbtbbtbt..",
    "..tbbbbbbt..",
    "..dbbbbbbd..",
    ".dddbbbbddd.",
    "dd..dddd..dd",
  ],
  ill: [
    "............",
    "...kkkkkk...",
    "..kllllllk..",
    ".kllllllllk.",
    ".klkklkkllk.",
    ".kllllllllk.",
    ".kllllllllk.",
    ".kllkkkklk..",
    "..klllllk...",
    "...kkkkkk...",
    "............",
    "............",
  ],
  sad: [
    "............",
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kyyyyyyyyk.",
    ".kykkyykkyk.",
    ".kyykyykyyk.",
    ".kyyuyyyyyk.",
    ".kyyukkkyyk.",
    "..kykyyykk..",
    "...kkkkkk...",
    "............",
    "............",
  ],
  smile: [
    "............",
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kyyyyyyyyk.",
    ".kyykyykyyk.",
    ".kyyyyyyyyk.",
    ".kykyyyykyk.",
    ".kyykkkkyyk.",
    "..kyyyyyyk..",
    "...kkkkkk...",
    "............",
    "............",
  ],
  // A closed book: red cover, dark spine, a title label and the page edge below.
  book: [
    "............",
    "..kkkkkkkkk.",
    ".kdrrrrrrrk.",
    ".kdrrrrrrrk.",
    ".kdrcccccrk.",
    ".kdrrrrrrrk.",
    ".kdrrrrrrrk.",
    ".kdrrrrrrrk.",
    ".kdkkkkkkkk.",
    ".kdccccccck.",
    "..kkkkkkkkk.",
    "............",
  ],
  leaf: [
    ".........gg.",
    "......gggGg.",
    "....gggllGg.",
    "...gglllGgg.",
    "..ggllGGgg..",
    "..glGGggg...",
    "..gGggg.....",
    ".gGgg.......",
    ".G..........",
    "G...........",
    "............",
    "............",
  ],
  spyglass: [
    "............",
    "..........kk",
    "........kkuk",
    "......kkttkk",
    ".....kttkk..",
    "....kttk....",
    "...kbbk.....",
    "..kbbk......",
    ".kbbk.......",
    ".kkk........",
    "............",
    "............",
  ],
  star: [
    ".....yy.....",
    ".....yy.....",
    "....yyyy....",
    "yyyyyyyyyyyy",
    ".yyyyoyyyyy.",
    "..yyyyyyyy..",
    "...yyyyyy...",
    "..yyyyyyyy..",
    "..yyy..yyy..",
    ".yy......yy.",
    ".y........y.",
    "............",
  ],
  lock: [
    "............",
    "....kkkk....",
    "...k....k...",
    "...k....k...",
    "..ssssssss..",
    "..sSSSSSSs..",
    "..sSSkkSSs..",
    "..sSSkkSSs..",
    "..sSSSSSSs..",
    "..ssssssss..",
    "............",
    "............",
  ],
  amphora: [
    "...kkkkkk...",
    "....kbbk....",
    "..k.kbbk.k..",
    "..kkbbbbkk..",
    "..kbbbbbbk..",
    "..kboooobk..",
    "..kbbbbbbk..",
    "..kboooobk..",
    "...kbbbbk...",
    "....kbbk....",
    "....kkkk....",
    "............",
  ],
  column: [
    "kkkkkkkkkkkk",
    "kcccccccccck",
    ".kkkkkkkkkk.",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    ".kkkkkkkkkk.",
    "kcccccccccck",
    "kkkkkkkkkkkk",
  ],
  castle: [
    "s.s.s..s.s.s",
    "sssss..sssss",
    "ssSss..ssSss",
    "ssssssssssss",
    "ssssssssssss",
    "ssssssssssss",
    "ssSsskksssSs",
    "sssskkkkssss",
    "sssskkkkssss",
    "sssskkkkssss",
    "SSSSSSSSSSSS",
    "............",
  ],
  factory: [
    ".ss.........",
    ".SS.........",
    ".SS..ss.....",
    ".SS..SS.....",
    ".SSS.SS.S..S",
    "SSSSSSSSSSSS",
    "SSSSSSSSSSSS",
    "SyySyySyySSS",
    "SSSSSSSSSSSS",
    "SSSSSSSSSSSS",
    "SSSSSSSSSSSS",
    "............",
  ],
  rocket: [
    ".....ww.....",
    "....wwww....",
    "....wuuw....",
    "....wwww....",
    "....wwww....",
    "....wwww....",
    "...rwwwwr...",
    "..rrwwwwrr..",
    "..r.oyyo.r..",
    "....oyyo....",
    ".....oo.....",
    "............",
  ],
  boat: [
    "......k.....",
    "......kw....",
    "......kww...",
    "......kwww..",
    "......kwwww.",
    "......k.....",
    "bbbbbbbbbbbb",
    ".bbbbbbbbbb.",
    "..dddddddd..",
    "uuuuuuuuuuuu",
    ".uu..uu..uu.",
    "............",
  ],
  bricks: [
    "............",
    "kkkkkkkkkkkk",
    "krrrkrrrrkrk",
    "kkkkkkkkkkkk",
    "krkrrrrkrrrk",
    "kkkkkkkkkkkk",
    "krrrkrrrrkrk",
    "kkkkkkkkkkkk",
    "krkrrrrkrrrk",
    "kkkkkkkkkkkk",
    "............",
    "............",
  ],
  scales: [
    ".....kk.....",
    ".kkkkkkkkkk.",
    ".k...kk...k.",
    "kyk..kk..kyk",
    "kyk..kk..kyk",
    "kkk..kk..kkk",
    ".....kk.....",
    ".....kk.....",
    "...kkkkkk...",
    "............",
    "............",
    "............",
  ],
  elder: [
    "...cccccc...",
    "..cccccccc..",
    "..cppppppc..",
    "..cpkppkpc..",
    "..cppppppc..",
    "..cpprrppc..",
    "..ccppppcc..",
    "...cccccc...",
    "....cccc....",
    "..vvvvvvvv..",
    ".vvvvvvvvvv.",
    ".vvvvvvvvvv.",
  ],
  skull: [
    "............",
    "...cccccc...",
    "..cccccccc..",
    ".cccccccccc.",
    ".ckkccccckk.",
    ".ckkccccckk.",
    ".cccccckccc.",
    "..cccccccc..",
    "...ckckck...",
    "...cccccc...",
    "............",
    "............",
  ],
  mammoth: [
    "....bbbbbb..",
    "..bbbbdbbbb.",
    ".bkbbbbdbbbb",
    ".bbbbbbbbdbb",
    "bbbbbbbbbbbb",
    "bcbbbbdbbbbb",
    "bccbbbbbbbb.",
    "b.cbbb..bbb.",
    "b..bb....bb.",
    "b..bb....bb.",
    "...dd....dd.",
    "............",
  ],
  hammer: [
    "............",
    ".ssssss.....",
    ".sSSSSsk....",
    ".ssssssk....",
    "...kbbk.....",
    "....bb......",
    ".....bb.....",
    "......bb....",
    ".......bb...",
    "........bb..",
    ".........bb.",
    "............",
  ],
  warning: [
    ".....kk.....",
    "....kyyk....",
    "....kyyk....",
    "...kyykyk...",
    "...kyykyk...",
    "..kyyykyyk..",
    "..kyyykyyk..",
    ".kyyyyyyyyk.",
    ".kyyyykyyyk.",
    "kyyyyyyyyyyk",
    "kkkkkkkkkkkk",
    "............",
  ],
  hand: [
    "...kkkkkkk..",
    "...kwwwwwk..",
    "..kwwwwwwwk.",
    ".kwwwwwwwwwk",
    "kwwwwwwwwwwk",
    "kwwkwwwwwwwk",
    ".kkkwwkwwkwk",
    "...kwwkwwkk.",
    "...kwwkkk...",
    "...kwwk.....",
    "...kwwk.....",
    "....kk......",
  ],
} satisfies Record<string, string[]>;

export type IconId = keyof typeof SPRITES;
