// Hand-drawn 12×12 pixel sprites. Each row is 12 characters; "." is empty and
// every other character is a colour from PALETTE. To add an icon, draw it here.
export const PALETTE: Record<string, string> = {
  k: "#2b2119",
  w: "#ffffff",
  c: "#f4efe6",
  r: "#d7263d",
  n: "#e8a0a0",
  o: "#f28c28",
  y: "#ffd23f",
  t: "#d9b45a",
  b: "#8b5a2b",
  d: "#5e3b1c",
  g: "#3fa34d",
  G: "#2d6e35",
  l: "#9fd356",
  s: "#a3a9ae",
  S: "#5f656b",
  u: "#4a90e2",
  U: "#1e4f9c",
  p: "#f1c7a0",
  m: "#b5651d",
  v: "#8e5cc2",
  // Teal: fusion plasma, aetherite.
  a: "#4fd8c4",
};

export const SPRITES = {
  flame: [
    ".....r......",
    ".....rr.....",
    "....ror.....",
    "...roor..r..",
    "...rooor.r..",
    "..rooyoorr..",
    "..royyyoor..",
    "..royyyyor..",
    "..royyyyor..",
    "...ryyyyr...",
    "....rrrr....",
    "............",
  ],
  beacon: [
    ".....r......",
    "....ror.....",
    "....oyo.....",
    "...bdbbdb...",
    "....d..d....",
    "....dd.d....",
    "....d.dd....",
    "....d..d....",
    "....dd.d....",
    "....d.dd....",
    "...dd..dd...",
    "..tttttttt..",
  ],
  campfire: [
    ".....r......",
    "....ror.....",
    "...rooor....",
    "...royor.r..",
    "..royyyor...",
    "..royyyor...",
    "...ryyyr....",
    ".d..rrr..d..",
    "..dd...dd...",
    "...ddddd....",
    "..dd...dd...",
    ".d.......d..",
  ],
  hut: [
    ".....kk.....",
    "....kttk....",
    "...kttttk...",
    "..kttttttk..",
    ".kttttttttk.",
    "kttttttttttk",
    ".kbbbbbbbbk.",
    ".kbbbddbbbk.",
    ".kbbbddbbbk.",
    ".kbbbddbbbk.",
    ".kkkkkkkkkk.",
    "............",
  ],
  basket: [
    "............",
    "...r..r.....",
    "..rrr.rr.r..",
    "...kkkkkkr..",
    "..k......k..",
    ".kkkkkkkkkk.",
    ".kttttttttk.",
    ".ktdtdtdtdk.",
    ".kttttttttk.",
    ".ktdtdtdtdk.",
    "..kttttttk..",
    "...kkkkkk...",
  ],
  axe: [
    "............",
    "..sss.......",
    ".sssss......",
    ".ssssSd.....",
    "..sssSdd....",
    "....Sddd....",
    ".....ddd....",
    "......ddd...",
    ".......ddd..",
    "........ddd.",
    ".........dd.",
    "............",
  ],
  wheat: [
    "...y...y..y.",
    "..yy..yy.yy.",
    "...y...y..y.",
    "..yy..yy.yy.",
    "...y...y..y.",
    "..yy..yy.yy.",
    "...g...g..g.",
    "...g...g..g.",
    "...g...g..g.",
    ".bbbbbbbbbbb",
    ".ddddddddddd",
    "............",
  ],
  shield: [
    "..kkkkkkkk..",
    ".krrrrrrrrk.",
    ".krrrrwrrrk.",
    ".krrrwwwrrk.",
    ".krrrrwrrrk.",
    ".krrrrwrrrk.",
    "..krrrrrrk..",
    "..krrrrrrk..",
    "...krrrrk...",
    "....krrk....",
    ".....kk.....",
    "............",
  ],
  sword: [
    "..........ss",
    ".........sws",
    "........sws.",
    ".......sws..",
    "......sws...",
    ".....sws....",
    "..y.sws.....",
    "...yws......",
    "...dy.......",
    "..dd.y......",
    ".dd.........",
    "kd..........",
  ],
  fish: [
    "............",
    "............",
    "...uuuu.....",
    "..uuuuuu..u.",
    ".uukwuuuuuu.",
    ".uuuuuuuuu..",
    ".UuuuuuuuuU.",
    "..UuuuuU..U.",
    "...UUUU.....",
    "............",
    "............",
    "............",
  ],
  pickaxe: [
    "...sssss....",
    "..sS...Ss...",
    ".sS..d..Ss..",
    ".s...d...s..",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    ".....d......",
    "............",
  ],
  rock: [
    "............",
    "............",
    "....ssss....",
    "..sssssss...",
    ".sssswsssS..",
    ".sssssssSS..",
    "ssssssSSSSS.",
    "sssssSSSSSS.",
    ".SSSSSSSSS..",
    "............",
    "............",
    "............",
  ],
  feather: [
    "..........cc",
    ".........ccc",
    "........cckc",
    ".......cckc.",
    "......cckc..",
    ".....cckc...",
    "....cckc....",
    "...cckc.....",
    "..cckc......",
    "..ckc.......",
    ".kk.........",
    "k...........",
  ],
  herb: [
    "............",
    "....gggg....",
    "....glgg....",
    "....gggg....",
    ".gggggggggg.",
    ".glllgggggg.",
    ".gggggggggg.",
    ".gggggggggg.",
    "....gggg....",
    "....gggg....",
    "....gggg....",
    "............",
  ],
  meat: [
    "............",
    "...nnnnn....",
    "..nrrrrrn...",
    ".nrrrrrrrn..",
    ".nrrrrrrrn..",
    ".nrrrrrrn...",
    "..nrrrrn....",
    "....ncc.....",
    ".....cc.....",
    "....c..c....",
    "....cc.cc...",
    "............",
  ],
  log: [
    "............",
    "............",
    "............",
    "..bbbbbbbbt.",
    ".bbbbbbbbttt",
    ".ddddddddtdt",
    ".bbbbbbbbttt",
    "..ddddddddt.",
    "............",
    "............",
    "............",
    "............",
  ],
  bulb: [
    "....yyyy....",
    "...yyyyyy...",
    "..yywyyyyy..",
    "..ywyyyyyy..",
    "..yyyyyyyy..",
    "...yyyyyy...",
    "....yyyy....",
    "....ssss....",
    "....SSSS....",
    "....ssss....",
    ".....SS.....",
    "............",
  ],
  coin: [
    "............",
    "...yyyyyy...",
    "..yyooooyy..",
    ".yyoyyyyoyy.",
    ".yoyyoyyyoy.",
    ".yoyyoyyyoy.",
    ".yoyyoyyyoy.",
    ".yyoyyyyoyy.",
    "..yyooooyy..",
    "...yyyyyy...",
    "............",
    "............",
  ],
  person: [
    "....kkkk....",
    "...kddddk...",
    "...kppppk...",
    "...kppppk...",
    "....kkkk....",
    "..kkmmmmkk..",
    ".kmmmmmmmmk.",
    ".kmkmmmmkmk.",
    ".kpkmmmmkpk.",
    "..kkmmmmkk..",
    "...kdkkdk...",
    "...kk..kk...",
  ],
  sheep: [
    "............",
    "...kkkkk....",
    "..kwwcwwk...",
    ".kwwwwwwwkkk",
    "kwwcwwwcwkwk",
    "kwwwwwwwwkkk",
    ".kwwwwwwwk..",
    "..kkkkkkk...",
    "..k.k..k.k..",
    "..k.k..k.k..",
    "............",
    "............",
  ],
  sapling: [
    "............",
    ".....gg.....",
    "....gllg....",
    "...glllg.g..",
    "....gllgglg.",
    ".g...bgglg..",
    "glg..b.gg...",
    ".gg..b......",
    "..g..b......",
    "..gg.b......",
    "...ddbdd....",
    "..dddddddd..",
  ],
  stump: [
    "............",
    "............",
    "............",
    "............",
    "...tttttt...",
    "..tbbbbbbt..",
    "..tbttttbt..",
    "..tbtbbtbt..",
    "..tbbbbbbt..",
    "..dbbbbbbd..",
    ".dddbbbbddd.",
    "dd..dddd..dd",
  ],
  // Someone sick in bed (pale green face under the blanket), and the bed once they're up.
  "bed-sick": [
    "............",
    "............",
    "............",
    "............",
    "............",
    "d...........",
    "dcc.........",
    "dclUuuuuuuu.",
    "dcluuuuuuuud",
    "dbbbbbbbbbbd",
    "d..........d",
    "............",
  ],
  "bed-empty": [
    "............",
    "............",
    "............",
    "............",
    "............",
    "d...........",
    "dcc.........",
    "dc....uuuuu.",
    "dcccuuuuuuud",
    "dbbbbbbbbbbd",
    "d..........d",
    "............",
  ],
  ill: [
    "............",
    "...kkkkkk...",
    "..kllllllk..",
    ".kllllllllk.",
    ".klkklkkllk.",
    ".kllllllllk.",
    ".kllllllllk.",
    ".kllkkkklk..",
    "..klllllk...",
    "...kkkkkk...",
    "............",
    "............",
  ],
  sad: [
    "............",
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kyyyyyyyyk.",
    ".kykkyykkyk.",
    ".kyykyykyyk.",
    ".kyyuyyyyyk.",
    ".kyyukkkyyk.",
    "..kykyyykk..",
    "...kkkkkk...",
    "............",
    "............",
  ],
  smile: [
    "............",
    "...kkkkkk...",
    "..kyyyyyyk..",
    ".kyyyyyyyyk.",
    ".kyykyykyyk.",
    ".kyyyyyyyyk.",
    ".kykyyyykyk.",
    ".kyykkkkyyk.",
    "..kyyyyyyk..",
    "...kkkkkk...",
    "............",
    "............",
  ],
  // A closed book: red cover, dark spine, a title label and the page edge below.
  book: [
    "............",
    "..kkkkkkkkk.",
    ".kdrrrrrrrk.",
    ".kdrrrrrrrk.",
    ".kdrcccccrk.",
    ".kdrrrrrrrk.",
    ".kdrrrrrrrk.",
    ".kdrrrrrrrk.",
    ".kdkkkkkkkk.",
    ".kdccccccck.",
    "..kkkkkkkkk.",
    "............",
  ],
  leaf: [
    ".........gg.",
    "......gggGg.",
    "....gggllGg.",
    "...gglllGgg.",
    "..ggllGGgg..",
    "..glGGggg...",
    "..gGggg.....",
    ".gGgg.......",
    ".G..........",
    "G...........",
    "............",
    "............",
  ],
  spyglass: [
    "............",
    "..........kk",
    "........kkuk",
    "......kkttkk",
    ".....kttkk..",
    "....kttk....",
    "...kbbk.....",
    "..kbbk......",
    ".kbbk.......",
    ".kkk........",
    "............",
    "............",
  ],
  star: [
    ".....yy.....",
    ".....yy.....",
    "....yyyy....",
    "yyyyyyyyyyyy",
    ".yyyyoyyyyy.",
    "..yyyyyyyy..",
    "...yyyyyy...",
    "..yyyyyyyy..",
    "..yyy..yyy..",
    ".yy......yy.",
    ".y........y.",
    "............",
  ],
  lock: [
    "............",
    "....kkkk....",
    "...k....k...",
    "...k....k...",
    "..ssssssss..",
    "..sSSSSSSs..",
    "..sSSkkSSs..",
    "..sSSkkSSs..",
    "..sSSSSSSs..",
    "..ssssssss..",
    "............",
    "............",
  ],
  amphora: [
    "...kkkkkk...",
    "....kbbk....",
    "..k.kbbk.k..",
    "..kkbbbbkk..",
    "..kbbbbbbk..",
    "..kboooobk..",
    "..kbbbbbbk..",
    "..kboooobk..",
    "...kbbbbk...",
    "....kbbk....",
    "....kkkk....",
    "............",
  ],
  column: [
    "kkkkkkkkkkkk",
    "kcccccccccck",
    ".kkkkkkkkkk.",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    "..kckckckk..",
    ".kkkkkkkkkk.",
    "kcccccccccck",
    "kkkkkkkkkkkk",
  ],
  castle: [
    "s.s.s..s.s.s",
    "sssss..sssss",
    "ssSss..ssSss",
    "ssssssssssss",
    "ssssssssssss",
    "ssssssssssss",
    "ssSsskksssSs",
    "sssskkkkssss",
    "sssskkkkssss",
    "sssskkkkssss",
    "SSSSSSSSSSSS",
    "............",
  ],
  factory: [
    ".ss.........",
    ".SS.........",
    ".SS..ss.....",
    ".SS..SS.....",
    ".SSS.SS.S..S",
    "SSSSSSSSSSSS",
    "SSSSSSSSSSSS",
    "SyySyySyySSS",
    "SSSSSSSSSSSS",
    "SSSSSSSSSSSS",
    "SSSSSSSSSSSS",
    "............",
  ],
  rocket: [
    ".....ww.....",
    "....wwww....",
    "....wuuw....",
    "....wwww....",
    "....wwww....",
    "....wwww....",
    "...rwwwwr...",
    "..rrwwwwrr..",
    "..r.oyyo.r..",
    "....oyyo....",
    ".....oo.....",
    "............",
  ],
  // Logs lashed together with vines.
  raft: [
    "............",
    "............",
    "............",
    "............",
    ".bbgbbbbgbb.",
    "bttgtttttgtb",
    "bbbgbbbbbgbb",
    "dddgdddddgdd",
    ".ddgddddgdd.",
    "uuuuuuuuuuuu",
    ".uu..uu..uu.",
    "............",
  ],
  boat: [
    "......k.....",
    "......kw....",
    "......kww...",
    "......kwww..",
    "......kwwww.",
    "......k.....",
    "bbbbbbbbbbbb",
    ".bbbbbbbbbb.",
    "..dddddddd..",
    "uuuuuuuuuuuu",
    ".uu..uu..uu.",
    "............",
  ],
  bricks: [
    "............",
    "kkkkkkkkkkkk",
    "krrrkrrrrkrk",
    "kkkkkkkkkkkk",
    "krkrrrrkrrrk",
    "kkkkkkkkkkkk",
    "krrrkrrrrkrk",
    "kkkkkkkkkkkk",
    "krkrrrrkrrrk",
    "kkkkkkkkkkkk",
    "............",
    "............",
  ],
  scales: [
    ".....kk.....",
    ".kkkkkkkkkk.",
    ".k...kk...k.",
    "kyk..kk..kyk",
    "kyk..kk..kyk",
    "kkk..kk..kkk",
    ".....kk.....",
    ".....kk.....",
    "...kkkkkk...",
    "............",
    "............",
    "............",
  ],
  elder: [
    "...cccccc...",
    "..cccccccc..",
    "..cppppppc..",
    "..cpkppkpc..",
    "..cppppppc..",
    "..cpprrppc..",
    "..ccppppcc..",
    "...cccccc...",
    "....cccc....",
    "..vvvvvvvv..",
    ".vvvvvvvvvv.",
    ".vvvvvvvvvv.",
  ],
  skull: [
    "............",
    "...cccccc...",
    "..cccccccc..",
    ".cccccccccc.",
    ".ckkccccckk.",
    ".ckkccccckk.",
    ".cccccckccc.",
    "..cccccccc..",
    "...ckckck...",
    "...cccccc...",
    "............",
    "............",
  ],
  mammoth: [
    "....bbbbbb..",
    "..bbbbdbbbb.",
    ".bkbbbbdbbbb",
    ".bbbbbbbbdbb",
    "bbbbbbbbbbbb",
    "bcbbbbdbbbbb",
    "bccbbbbbbbb.",
    "b.cbbb..bbb.",
    "b..bb....bb.",
    "b..bb....bb.",
    "...dd....dd.",
    "............",
  ],
  hammer: [
    "............",
    ".ssssss.....",
    ".sSSSSsk....",
    ".ssssssk....",
    "...kbbk.....",
    "....bb......",
    ".....bb.....",
    "......bb....",
    ".......bb...",
    "........bb..",
    ".........bb.",
    "............",
  ],
  warning: [
    ".....kk.....",
    "....kyyk....",
    "....kyyk....",
    "...kyykyk...",
    "...kyykyk...",
    "..kyyykyyk..",
    "..kyyykyyk..",
    ".kyyyyyyyyk.",
    ".kyyyykyyyk.",
    "kyyyyyyyyyyk",
    "kkkkkkkkkkkk",
    "............",
  ],
  hand: [
    "...kkkkkkk..",
    "...kwwwwwk..",
    "..kwwwwwwwk.",
    ".kwwwwwwwwwk",
    "kwwwwwwwwwwk",
    "kwwkwwwwwwwk",
    ".kkkwwkwwkwk",
    "...kwwkwwkk.",
    "...kwwkkk...",
    "...kwwk.....",
    "...kwwk.....",
    "....kk......",
  ],
  well: [
    "....dddd....",
    "..dddddddd..",
    ".dd......dd.",
    "...b....b...",
    "...b..k.b...",
    "...b..s.b...",
    "...b....b...",
    "..ssssssss..",
    ".suuuuuuuus.",
    ".ssssssssss.",
    ".sSsSsSsSss.",
    "..ssssssss..",
  ],
  aqueduct: [
    "............",
    "uuuuuuuuuuuu",
    "ssssssssssss",
    "sSssSssSssSs",
    "ss..ssss..ss",
    "s....ss....s",
    "s....ss....s",
    "s....ss....s",
    "s....ss....s",
    "s....ss....s",
    "s....ss....s",
    "gggggggggggg",
  ],
  mill: [
    "....dddd....",
    "..dd.dd.dd..",
    ".d...dd...d.",
    ".d.d.dd.d.d.",
    "d...dddd...d",
    "dddddbbddddd",
    "dddddbbddddd",
    "d...dddd...d",
    ".d.d.dd.d.d.",
    ".d...dd...d.",
    "..dd.dd.dd..",
    "uuuudddduuuu",
  ],
  insula: [
    "............",
    "..rrrrrrrr..",
    ".rrrrrrrrrr.",
    ".tttttttttt.",
    ".tdtdttdtdt.",
    ".tttttttttt.",
    ".tdtdttdtdt.",
    ".tttttttttt.",
    ".tdtdttdtdt.",
    ".tttttttttt.",
    ".ttttddtttt.",
    ".ttttddtttt.",
  ],
  drop: [
    ".....uu.....",
    ".....uu.....",
    "....uuuu....",
    "....uuuu....",
    "...uuuuuu...",
    "...uuuuuu...",
    "..uwuuuuuu..",
    "..uwuuuuuu..",
    "..uwwuuuuu..",
    "..uuuuuuuu..",
    "...uuuuuu...",
    "....uuuu....",
  ],
  baths: [
    "...w...w....",
    "..w...w...w.",
    "...w...w..w.",
    "..w...w...w.",
    "............",
    ".ssssssssss.",
    "ssuuuuuuuuss",
    "suuwuuuuwuus",
    "suuuuuuuuuus",
    "ssuuuuuuuuss",
    ".ssssssssss.",
    "............",
  ],
  market: [
    "............",
    "rwrwrwrwrwrw",
    "rwrwrwrwrwrw",
    ".rwrwrwrwrw.",
    ".b........b.",
    ".b........b.",
    ".b.yy.oo..b.",
    ".bbbbbbbbbb.",
    ".bddddddddb.",
    ".bd......db.",
    ".bd......db.",
    ".bb......bb.",
  ],
  sun: [
    ".....y......",
    ".y...y...y..",
    "..y.....y...",
    "....ooo.....",
    "...ooyoo....",
    "yy.oyyyo.yy.",
    "...ooyoo....",
    "....ooo.....",
    "..y.....y...",
    ".y...y...y..",
    ".....y......",
    "............",
  ],
  storm: [
    "...ssss.....",
    "..ssssss....",
    ".ssssssss...",
    "sssSsssssss.",
    "ssssssssss..",
    "....yy......",
    "...yy.......",
    "..yyyy......",
    "....yy.u..u.",
    "...yy.u..u..",
    "..y..u..u...",
    "............",
  ],
  flood: [
    "............",
    "....bb......",
    "...bddb.....",
    "..bddddb....",
    "..bdkdkb....",
    "uuuuuuuuuuuu",
    "UuuuUuuuUuuu",
    "uuuuuuuuuuuu",
    "wuuuwuuuwuuu",
    "uuuuuuuuuuuu",
    "UUUUUUUUUUUU",
    "............",
  ],
  quake: [
    "............",
    "....k.......",
    "...k........",
    "gggkggkggggg",
    "bbbbkbkbbbbb",
    "bbbkbbbkbbbb",
    "bbkbbbbbkbbb",
    "bbbkbbbbbkbb",
    "bbbbkbbbkbbb",
    "bbbbbkbkbbbb",
    "dddddddddddd",
    "............",
  ],
  landslide: [
    "k...........",
    "ss..........",
    "sSs.........",
    "sssS..s.....",
    "ssSss..S....",
    "sssssS..s...",
    "ssSsssss.S..",
    "sssssssss.s.",
    "ssssSsssss.s",
    "bbbbbbbbbbbb",
    "dddddddddddd",
    "............",
  ],
  church: [
    ".....y......",
    "....yyy.....",
    ".....y......",
    ".....s......",
    "....sSs.....",
    "...sssss....",
    "..sssSsss...",
    "..ssuuuss...",
    "..ssuUuss...",
    "..sssssss...",
    "..sssddss...",
    "..sssddss...",
  ],
  anchor: [
    "....SSS.....",
    "....S.S.....",
    "....SSS.....",
    ".....S......",
    "...SSSSS....",
    ".....S......",
    ".....S......",
    ".....S......",
    "S....S....S.",
    "SS...S...SS.",
    ".SS..S..SS..",
    "..SSSSSSS...",
  ],
  windmill: [
    "b.........b.",
    ".b.......b..",
    "..b.....b...",
    "...b...b....",
    "....bkb.....",
    "....kck.....",
    "...bcccb....",
    "..b.ccc.b...",
    ".b..ccc..b..",
    "b...ccc...b.",
    "....cdc.....",
    "....cdc.....",
  ],
  plough: [
    "............",
    "..........b.",
    ".........b..",
    "........b...",
    ".......b....",
    "......b.....",
    ".....bb.....",
    "...SSbb.....",
    "..SSSSb.....",
    ".SSSSS......",
    "dddddddddddd",
    "dmdmdmdmdmdm",
  ],
  horse: [
    "............",
    ".........kk.",
    "........bbbk",
    ".......bbbbb",
    "......bbb...",
    ".bbbbbbbb...",
    "bbbbbbbbb...",
    "k.bbbbbbb...",
    "k.b.b..b.b..",
    "..b.b..b.b..",
    "..b.b..b.b..",
    "..k.k..k.k..",
  ],
  dove: [
    "............",
    "........ww..",
    ".......wwkw.",
    "......wwwwwo",
    "..w..wwwww..",
    ".wwwwwwwww..",
    "wwwwwwwwww..",
    ".wwwwwwww...",
    "..wwwwww....",
    "....w.g.....",
    ".....ggg....",
    "......g.....",
  ],
  scroll: [
    "............",
    ".tttttttttt.",
    "tbtcccccctbt",
    ".t.cccccc.t.",
    "...ckkkkc...",
    "...cccccc...",
    "...ckkkkc...",
    "...cccccc...",
    "...ckkkcc...",
    ".t.cccccc.t.",
    "tbtcccccctbt",
    ".tttttttttt.",
  ],
  press: [
    "............",
    "..bbbbbbbb..",
    "..b..SS..b..",
    "..b..SS..b..",
    "..b.SSSS.b..",
    "..b.kkkk.b..",
    "..b......b..",
    "..bccccccb..",
    "..bckkkkcb..",
    "bbbbbbbbbbbb",
    ".b........b.",
    ".b........b.",
  ],
  crown: [
    "............",
    "............",
    ".y...y...y..",
    ".yy.yyy.yy..",
    ".yyyyyyyyy..",
    ".yyryyyuyy..",
    ".yyyyyyyyy..",
    ".tttttttttt.",
    "............",
    "............",
    "............",
    "............",
  ],
  rat: [
    "............",
    "............",
    "............",
    "...SS.......",
    "..SSSSSS....",
    ".kSSSSSSS...",
    "SSSSSSSSSS..",
    ".SSSSSSSSSn.",
    "..S.S..S.S.n",
    "...........n",
    "..........n.",
    "............",
  ],
  moon: [
    "............",
    "....cccc....",
    "...cccc.....",
    "..cccc......",
    "..ccc.......",
    "..ccc.......",
    "..ccc.......",
    "..cccc......",
    "...cccc.....",
    "....cccc....",
    "............",
    "............",
  ],
  "person-sit": [
    "............",
    "....kkkk....",
    "...kddddk...",
    "...kppppk...",
    "...kppppk...",
    "....kkkk....",
    "..kkmmmmkk..",
    ".kmmmmmmmmk.",
    ".kpkmmmmkpk.",
    "..kkmmmmkkkk",
    "...kddddddpk",
    "...kkkkkkkk.",
  ],
  "elder-sit": [
    "............",
    "............",
    "...cccccc...",
    "..cccccccc..",
    "..cppppppc..",
    "..cpkppkpc..",
    "..cppppppc..",
    "..ccpprpcc..",
    "...cccccc...",
    "..vvvvvvvv..",
    ".vvvvvvvvvvv",
    "vvvvvvvvvvvv",
  ],
  "spear": [
    "..........s.",
    ".........sSs",
    "........sSs.",
    ".......bss..",
    "......b.....",
    ".....b......",
    "....b.......",
    "...b........",
    "..b.........",
    ".b..........",
    "b...........",
    "............",
  ],
  "flint": [
    "............",
    ".....SS.....",
    "....SsSS....",
    "...SsssSS...",
    "...SssSsS...",
    "..SsssssSS..",
    "..SsSsssSS..",
    "..SssssSsS..",
    "...SsssssS..",
    "....SssSS...",
    ".....SSS....",
    "............",
  ],
  "sprout": [
    "............",
    "............",
    "............",
    "............",
    ".....g......",
    "....gll.....",
    "...ll.g.....",
    "......g.....",
    "......g.....",
    "......g.....",
    "..ddddddd...",
    ".ddddddddd..",
  ],
  "hide": [
    "............",
    ".....tt.....",
    "..m..tt..m..",
    "..mmmttmmm..",
    "...mtttttm..",
    "...ttmtttt..",
    "..tttttmtt..",
    "..ttmttttt..",
    "...tttmtt...",
    "..mmmttmmm..",
    "..m..tt..m..",
    ".....t......",
  ],
  "tunic": [
    "............",
    "...mm..mm...",
    "..mmmkkmmm..",
    ".mmmmmmmmmm.",
    ".mmmmmmmmmm.",
    ".mm.mtmm.mm.",
    "....mmtm....",
    "....mmmt....",
    "....mmmm....",
    "....mtmm....",
    "....mmmm....",
    "............",
  ],
  "tablet": [
    "............",
    "..mmmmmmmm..",
    ".mttttttttm.",
    ".mtktkttktm.",
    ".mttttttttm.",
    ".mtkkttkktm.",
    ".mttttttttm.",
    ".mtktkkttkm.",
    ".mttttttttm.",
    ".mtkttktktm.",
    "..mmmmmmmm..",
    "............",
  ],
  "ore": [
    "............",
    "............",
    "....SSS.....",
    "...SlgSS....",
    "..SSgGlSS...",
    ".SlsSSgSsS..",
    ".SgGSlSSgS..",
    ".SSSsSgGSS..",
    "..SlgSSSs...",
    "...SSSSS....",
    "............",
    "............",
  ],
  "cart": [
    "............",
    "............",
    "............",
    "..bbbbbbbbb.",
    "..bmmmmmmmb.",
    "..bmmmmmmmbb",
    "..bbbbbbbbbb",
    "...kk...kk..",
    "..kssk.kssk.",
    "..ksdk.ksdk.",
    "...kk...kk..",
    "............",
  ],
  "road": [
    "............",
    "............",
    "............",
    "............",
    "SsssSsssSsss",
    "SsssSsssSsss",
    "SSSSSSSSSSSS",
    "ssSsssSsssSs",
    "ssSsssSsssSs",
    "SSSSSSSSSSSS",
    "............",
    "............",
  ],
  "jade": [
    "............",
    "............",
    ".....GG.....",
    "....GllG....",
    "...GlgglG...",
    "..GgglggGG..",
    "..GgggglgG..",
    "..GGgggggG..",
    "...GGgggG...",
    "....GGGG....",
    "............",
    "............",
  ],
  bird: [
    "............",
    "............",
    "............",
    "..kk....kk..",
    "...kk..kk...",
    "....kkkk....",
    "....kSSkk...",
    "...kSSSSko..",
    "....kkkk....",
    ".....kk.....",
    "............",
    "............",
  ],
  torch: [
    ".....r......",
    "....ror.....",
    "....oyo.r...",
    "...royyor...",
    "....ryyr....",
    ".....kk.....",
    ".....bb.....",
    ".....bb.....",
    ".....bd.....",
    ".....bd.....",
    ".....bd.....",
    ".....dd.....",
  ],
  mud: [
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "............",
    "...dddddd...",
    ".ddbdddbddd.",
    "ddddbdddddbd",
    ".dddddbdddd.",
    "...dddddd...",
  ],
  // A floating needle in a bowl of water: the first compasses. Red end north.
  compass: [
    "............",
    "....bbbb....",
    "..bbuuuubb..",
    ".buuuuruuub.",
    ".buuuurruub.",
    "buuuuurruuub",
    "buuuuSSuuuub",
    ".buuuSSuuub.",
    ".buuuuSuuub.",
    "..bbuuuubb..",
    "....bbbb....",
    "............",
  ],
  // ---- Industrial & Modern era ----
  // A steam locomotive: smoke from the chimney at the front, the cab behind.
  train: [
    "..s.........",
    ".sss........",
    ".SS.........",
    ".SS....kkkk.",
    ".SS....kuuk.",
    "rrrrrrrkuuk.",
    "rrrrrrrkkkk.",
    "ryrrrrrkkkk.",
    "kkkkkkkkkkkk",
    ".SkS.SkS.SkS",
    "..k...k...k.",
    "............",
  ],
  // A cooling tower letting off steam, and a striped chimney with smoke.
  powerplant: [
    "...ss....ss.",
    "..ssss..ss..",
    "...ss....s..",
    ".cccccc..r..",
    "..cccc...w..",
    "..cccc...r..",
    ".cccccc..w..",
    "cccccccc.r..",
    "cccccccc.w..",
    "SSSSSSSSSSSS",
    "SyySSyySSyyS",
    "SSSSSSSSSSSS",
  ],
  // A concrete dam: the lake behind, the spillway, the river below.
  dam: [
    "............",
    "uuuuuuuuuuuu",
    "uuuuuuuuuuuu",
    "ssssssssssss",
    "sSssssssssSs",
    ".ssssuussss.",
    "..sssuusss..",
    "..sssuusss..",
    "...ssuuss...",
    "uuuuuuuuuuuu",
    "UuuuUuuuUuuu",
    "............",
  ],
  // A wind turbine: three blades on a tall tower.
  turbine: [
    ".....s......",
    ".....s......",
    ".....s......",
    ".....s......",
    "....sSs.....",
    "...s.c.ss...",
    "..s..c...ss.",
    ".s...c......",
    ".....c......",
    ".....c......",
    "....scs.....",
    "..gggggggg..",
  ],
  // Rows of solar panels on legs.
  solar: [
    "............",
    "............",
    "...UUUUUUUU.",
    "..UuUuUuUuU.",
    "..UUUUUUUUU.",
    ".UuUuUuUuU..",
    ".UUUUUUUUU..",
    "UuUuUuUuU...",
    "UUUUUUUUU...",
    "..S.....S...",
    "..S.....S...",
    "gggggggggggg",
  ],
  // A white hospital with a red cross.
  hospital: [
    "............",
    "..cccccccc..",
    ".cccccccccc.",
    ".ccccrrcccc.",
    ".cccrrrrccc.",
    ".ccccrrcccc.",
    ".cccccccccc.",
    ".cuuccccuuc.",
    ".cuuccccuuc.",
    ".ccccddcccc.",
    ".ccccddcccc.",
    "ssssssssssss",
  ],
  // Two trees, a bench and a path.
  park: [
    "............",
    "..GG.....GG.",
    ".GggG...GggG",
    "GgglgG.GgglG",
    "GggggG.GgggG",
    ".GggG...GGG.",
    "..dd.....d..",
    "..dd.....d..",
    "...bbbbbb...",
    "...b....b...",
    "llllllllllll",
    "lllttttlllll",
  ],
  // A stone sea wall with the waves breaking against it.
  seawall: [
    "............",
    "............",
    "............",
    "ssssssssssss",
    "sSsSsSsSsSsS",
    "ssssssssssss",
    "SsSsSsSsSsSs",
    "ssssssssssss",
    "wuwuuwuwuuwu",
    "uuuuuuuuuuuu",
    "UuUuUuUuUuUu",
    "uuuuuuuuuuuu",
  ],
  // An old computer: a screen of green text and a keyboard.
  computer: [
    "............",
    ".SSSSSSSSSS.",
    ".SUUUUUUUUS.",
    ".SUlUUUUUUS.",
    ".SUUllUUUUS.",
    ".SUUUUUlUUS.",
    ".SUUUUUUUUS.",
    ".SSSSSSSSSS.",
    ".....SS.....",
    "...SSSSSS...",
    ".ssssssssss.",
    ".sSsSsSsSss.",
  ],
  // A tank, its gun to the right.
  tank: [
    "............",
    "............",
    "............",
    "....GGGG....",
    "....GGGGkkkk",
    "..GGGGGGGG..",
    ".GGGGGGGGGG.",
    "kkkkkkkkkkkk",
    "kSkSkSkSkSkS",
    ".kkkkkkkkkk.",
    "............",
    "............",
  ],
  // ---- Future & Space era (and the Industrial era's nuclear power) ----
  // A nuclear plant: a cooling tower letting off steam, and the reactor dome.
  reactor: [
    "..ss........",
    ".ssss.......",
    "..ss........",
    ".cccc.......",
    "..cc........",
    "..cc....kk..",
    ".cccc..kssk.",
    ".cccc.ksssk.",
    "cccccckssssk",
    "cccccckssssk",
    "SSSSSSSSSSSS",
    "SyySSSSSSyyS",
  ],
  // A fusion reactor: a glowing ring of plasma inside a dome.
  fusion: [
    "............",
    "....kkkk....",
    "..kkcccckk..",
    ".kcccccccck.",
    ".kcaaaaaack.",
    "kcaccccccack",
    "kcaccccccack",
    ".kcaaaaaack.",
    ".kcccccccck.",
    "SSSSSSSSSSSS",
    "SsSsSsSsSsSs",
    "SSSSSSSSSSSS",
  ],
  // A data center: racks of computers with blinking lights.
  datacenter: [
    "............",
    "............",
    "kkkkkkkkkkkk",
    "kSSSkSSSkSSk",
    "kSlSkSaSkSlk",
    "kSSSkSSSkSSk",
    "kSaSkSlSkSak",
    "kSSSkSSSkSSk",
    "kSlSkSaSkSlk",
    "kSSSkSSSkSSk",
    "kkkkkkkkkkkk",
    "ssssssssssss",
  ],
  // A machine that pulls carbon out of the air: a wall of big fans.
  capture: [
    "............",
    "..s.....s...",
    ".s.......s..",
    "kkkkkkkkkkkk",
    "ksSsksSskSsk",
    "kSsSkSsSkSsk",
    "ksSskSsskSsk",
    "kkkkkkkkkkkk",
    "kcccccccccck",
    "kccgggggccck",
    "kkkkkkkkkkkk",
    "ssssssssssss",
  ],
  // A vertical farm: floor upon floor of plants under lights.
  vfarm: [
    "....kkkk....",
    "...kuuuuk...",
    "...kgglgk...",
    "...kuuuuk...",
    "...klgggk...",
    "...kuuuuk...",
    "...kgglgk...",
    "...kuuuuk...",
    "...klgggk...",
    "...kuuuuk...",
    "...kddddk...",
    "ssssssssssss",
  ],
  // An arcology: a whole city in one tall tower, with gardens on every level.
  arcology: [
    ".....kk.....",
    "....kcck....",
    "....kcck....",
    "...kgcclk...",
    "...kcccck...",
    "..kglccglk..",
    "..kccuucck..",
    ".kgccccccgk.",
    ".kccuccucck.",
    "kglccccccglk",
    "kccccddcccck",
    "ssssssssssss",
  ],
  // An ocean clean-up boat with its long boom catching plastic.
  cleaner: [
    "............",
    "....k.......",
    "....kk......",
    "...kccck....",
    "..kcccccck..",
    ".krrrrrrrrk.",
    "..kkkkkkkk..",
    "uuuuuuuuuuuu",
    "uyuyuyuyuyuu",
    "UuuuUuuuUuuu",
    "uuuuuuuuuuuu",
    "UuUuUuUuUuUu",
  ],
  // A satellite with two solar wings.
  satellite: [
    "............",
    "............",
    "UU.......UU.",
    "UuU.....UuU.",
    "UUU.kkk.UUU.",
    "UuUkscskkUuU",
    "UUUkscskUUU.",
    "UuU.kkk.UuU.",
    "UU...s...UU.",
    ".....s......",
    "....sss.....",
    "............",
  ],
  // A friendly robot.
  robot: [
    "....kkkk....",
    "...kssssk...",
    "...ksaask...",
    "...kssssk...",
    "....kkkk....",
    "..kksssskkk.",
    ".ksksssskk..",
    ".k.ksssskk..",
    "...ksssskk..",
    "...kk..kk...",
    "...ks..ks...",
    "..kkk..kkk..",
  ],
  // Aetherite: an unidentified crystal that hums.
  aetherite: [
    "............",
    ".....a......",
    "....aca.....",
    "....aca..a..",
    "...aacaa.aa.",
    "...acccaaca.",
    "..aacccaacca",
    "..acccccacca",
    "..acccccaaca",
    "...aaaaaaaa.",
    "..SSSSSSSSS.",
    "............",
  ],
  // Mineral X-7: an unidentified cluster from under the sea floor.
  mineralx: [
    "............",
    "............",
    "...v....v...",
    "..vnv..vnv..",
    "..vnv.vnnv..",
    ".vnnvvnnnv..",
    ".vnnnvnnnvv.",
    ".vnnnvnnvnv.",
    "..vvvvvvvnv.",
    "...SSSSSSSS.",
    "..SSSSSSSSSS",
    "............",
  ],
  // Uranium ore, faintly glowing.
  uranium: [
    "............",
    "............",
    "....SSSS....",
    "...SSlSSS...",
    "..SSSSSlSS..",
    "..SlSSSSSS..",
    ".SSSSSlSSSS.",
    ".SSlSSSSSlS.",
    ".SSSSSSSSSS.",
    "..SSSSSSSS..",
    "............",
    "............",
  ],
  // The whole planet: sea, land and clouds.
  earth: [
    "....kkkk....",
    "..kkuuuukk..",
    ".kuugguuuuk.",
    ".kuggguucuk.",
    "kuuuggguuuuk",
    "kuccuguugguk",
    "kuuuuuuggguk",
    "kuuguuuugguk",
    ".kugguuuuuk.",
    ".kuuuuccuuk.",
    "..kkuuuukk..",
    "....kkkk....",
  ],
  // Sound on (the speaker in the top bar).
  speaker: [
    "............",
    ".....kk.....",
    "....kcck..w.",
    "kkkkccck...w",
    "kcccccck.w.w",
    "kcccccck.w.w",
    "kcccccck.w.w",
    "kcccccck.w.w",
    "kkkkccck...w",
    "....kcck..w.",
    ".....kk.....",
    "............",
  ],
  // Sound off.
  speakerOff: [
    "............",
    ".....kk.....",
    "....kcck....",
    "kkkkccck....",
    "kcccccck....",
    "kcccccck.r.r",
    "kcccccck..r.",
    "kcccccck.r.r",
    "kkkkccck....",
    "....kcck....",
    ".....kk.....",
    "............",
  ],
} satisfies Record<string, string[]>;

export type IconId = keyof typeof SPRITES;
