// What's new, newest first. Shown at the top of the landing page and the title
// screen. Add a line here for every change a player would notice.
export interface Update {
  date: string; // YYYY-MM-DD
  items: string[];
}

export const UPDATES: Update[] = [
  {
    date: "2026-10-05",
    items: [
      "The UN Sustainable Development Goals section now uses the official icons for Goals 7, 11, 13 and 15, with an attribution and disclaimer.",
      "Accessibility has its own top-right box on the project page and in the app, including a saved master sound-volume slider. Town Houses now have a gabled roof and clearer window trim; Industrial Apartment Blocks have a quieter steel-and-glass facade.",
    ],
  },
  {
    date: "2026-10-01",
    items: [
      "Every new game opens with the fly-in over your island now: Build to Last and multiplayer too, not just the Stone Age.",
      "See a building's reach before you build it: while placing a quarry, campfire, factory, aqueduct, mill or anything that connects, the tiles it would affect light up, red where it does harm and green where it helps, and the buildings it would hit stand out.",
      "Buildings connect: aqueducts can join up in a chain to carry river water inland (each linked one waters the fields near it, and a chain brings water for more people), and some buildings work better side by side, joined by a short path: a farm by a granary, a market by homes, schools by libraries, a factory by a station and more. The placement card says what a spot connects to.",
      "Two main ways to play, side by side: From the Stone Age, or Build to Last from 1850. Both are on the title screen, the website and How to play. The title screen no longer has an \"I've played before\" button; skip the tutorial from the tutorial itself.",
      "Hunters only hunt when the tribe needs food. When the stores are full, they gather wood at their camp instead, and the herds get a rest.",
      "Build to Last starts with 30 Knowledge, as intended: the town you start with no longer counts as \"firsts\" or a chief level-up, which used to double it in the first seconds.",
      "Sending settlers now has a price: each one takes 15 food and 5 wood for the road, you lose their work, and the families left behind are sadder for a while.",
      "Build to Last, tidier: the starting town is laid out in districts (homes in the middle, farms around them, industry together on one side), the build bar leaves out Stone Age buildings and the army, scouts and ships, and a short card explains the three problems before the clock starts. Click any of the three problems at the top to see how to solve it. The river choice now says what each side gains and gives up.",
      "New game mode, Build to Last: start in 1850 with a smoky industrial town and solve three big problems (clear the air, clean power, a home and food for 120 with the forest standing). 30 new short advancements, no tutorial and no lessons.",
      "First-time mode is calmer: in the Stone Age there are no raids or natural disasters, big moments are three times further apart, and lessons and small moments come half as often. Event cards stay spaced out for the first half hour.",
      "Cutscenes move like the opening fly-in: a new era sweeps down from high over the sea to your town, and discovery scenes open with the camera moving in.",
      "Tired people sweat: when your town is overworked, drops of sweat fly off your villagers' brows, more of them the more tired the town is.",
      "The project page moves: pixel clouds drift, embers rise, the title comes in line by line, the Play button glows, and the cards slide in as you scroll. It all stays still if your device asks for less motion.",
      "Watch the fights: when your warriors meet raiders, the camera goes in close over the battle (click to leave). In multiplayer, the raider gets a view of the fight, anyone else can choose to watch, and everyone hears how it ended.",
      "Hunters no longer jitter back and forth at rivers: they plan a way round the water, and only go after animals they can actually reach. Villagers who can't reach a log seat no longer sit on the bare ground by the fire.",
      "Multiplayer bots adapt to you: in a race they keep pace with the players in the room instead of racing ahead, so a good game wins and a close one stays close. Their raids are sized to your defence, so a town with warriors can always beat them.",
      "Chat in multiplayer: talk in the waiting room and during the match (Chat in the side menu), with quick phrases for phones. New messages show a count and a short preview.",
      "The game and the project page have a little pixel flame in the browser tab.",
      "The project page shows the whole journey now: screenshots of a Stone Age camp, a Medieval town, an Industrial city and a Future city, and the four UN goals the game teaches most (Cities, Climate, Life on Land, Clean Energy).",
      "A How to play guide: the whole game on one page, from the title screen or the in-game Menu.",
      "People get tired when there are more jobs than workers: tired people make less and are less happy. Warriors help with the work half the time. Learn Rest Days to recover faster.",
      "Eight new advancements: Basketry, Smoking Fish, Seed Saving, Tamed Dogs, Kilns, Star Charts, Rest Days and Town Watch. Each does something different (food that keeps, faster canoes, earlier raid warnings and more).",
      "The Roman legion is bigger, and a small band of Roman scouts lands first to test your defences.",
      "Fires look much better: flickering tongues of flame that sway, a hot bright core, glowing embers, rising sparks and a soft glow.",
      "The land tiles now meet edge to edge (no more sea showing through the gaps), and worn-down buildings have broken planks and fallen stones around them; a broken one is scorched, with a fallen beam.",
      "Fixes: a building's info panel now stays on screen (docked at the side) instead of running off the top when zoomed in, and markers on the map no longer draw over the goal and other panels.",
      "Choose where to explore: press Scout or Canoe, then click a spot (in the fog for scouts, on the sea or another island for canoes). Further away takes longer. You can watch the scouts walk out and back, and the canoe paddle there and home again; whatever they saw is mapped when they return.",
      "Shells are useful from the start: press Trade to swap them for food, wood or stone (each trade makes the next a little dearer; prices ease back). The Trade button gets a ! when shells pile up. You can also pay raiders off in shells instead of food.",
      "Livelier raids: raiders come ashore in groups that fan out and close in from the sides, and fights are a real melee. Each fighter circles an opponent, darts in to strike and backs off; the fallen are knocked back, survivors gang up on whoever is left, and the losers scatter while the winners give chase.",
      "Play together: up to 4 players on the same island, by a 4-letter code, a shared link or an open room; bots take the empty seats. Race (most Chief XP when time runs out wins; send gifts, or warriors to raid each other) or co-op (reach the team target together). Quick, normal or long matches learn 3x, 2x or 1x as fast; a new era is worth 4x the XP, and damaged land costs XP every minute. The match sits in a small menu on the right.",
      "Clearer text: the pixel font no longer joins letters together, so \"fire\" stops looking like \"Are\" and \"fills\" like \"Alls\".",
      "New era: Industrial & Modern. Come through the Black Death, learn Steam & Coal and grow to 90 people. Factories, railways, apartment blocks and a power grid; coal is cheap but its carbon stays in the air for good and its smog makes people ill. Switch to water, wind, sun or nuclear power (its waste lasts thousands of years). The era ends in a climate crisis: heat, storms and floods at once, worse the more carbon you burned.",
      "New era: Future & Space, the last one. A climate tipping point: get the air back down to 350 ppm in time with Air Capture Plants, forests and Rewilding, or the climate tips for good. AI, automation (more of everything, but people lose their jobs until a Shorter Work Week), vertical farms, arcologies, fusion, ocean clean-up, and a Launch Site with a view of the planet from orbit: satellites, a space telescope, power from orbit and a Moon base. The game ends at Type I on the Kardashev scale: the whole planet on clean energy, with the land still healthy.",
      "Uranium, plutonium and two minerals nobody can name are real now: nuclear power and breeder reactors in the Industrial era; Mineral X-7 (power with almost no loss) and Aetherite from the Moon (the best building improvement) in the Future.",
      "Apartment blocks and arcologies keep their people warm when the power is on, and the end-of-era summaries now say how each era really ended.",
      "Phones: the HUD is much tidier. The top bar takes two rows, the six meters sit in one strip under it (tap one to see why), the goal fits on one line (tap to read it all), only the newest message shows, and the build bar is smaller.",
      "Hide the build bar with the ▼ Hide button to see more of the island; ▲ Build brings it back. It comes back by itself when a hint or the tutorial needs it.",
      "Improve your buildings: click a farm, woodcutter, quarry, home and more, and press Improve. Stone-built first, then Bronze-fitted, Iron-bound (new: Iron Tools) and Steel-framed (new: Steelmaking). Each level makes 25% more from the same land, or gives a home more room. Uranium, plutonium and two minerals nobody can name wait in the Advancements for later eras.",
      "Discovery cutscenes now show the era in the background: huts, then columns and aqueducts, castles and windmills, smoky factories, and rockets under a ringed planet.",
      "Realistic time (a joke, on the title screen): the calendar runs in real time, with today's date, the hour and the season, in 50,000 BCE. The next era is only about 47,000 real years away.",
      "Beliefs: in the Ancient era build a Shrine (a carved spirit pole): it cheers people up, and every year the village holds a festival that costs some food. In the Classical era a Temple adds happiness and teaches reading, and the people decide whether to honour the river (no mills or aqueducts, healthier land) or tame it.",
      "People keep away from danger: nobody walks into a burning wildfire, and hunters walk round buildings and fires instead of straight through them.",
      "The Watch Fire is now a Watch Tower: a tall lookout tower with a ladder, a thatched roof and a lookout on top. Same job (raiders seen sooner, a little defense), no fire.",
      "Elder Ama now introduces every feature the tutorial skips, right when it first matters: selling a woodcutter the sacred grove has cut off, what scouting costs, planting saplings, training warriors before a raid, speeding up time and more. One short line at a time, and the button she means glows.",
      "Warm Clothes now really replaces campfires: each Livestock Pen clothes 10 people, and families cook at small hearths in their homes, so with enough pens you need no campfire at all.",
      "Population control: click the population counter to hold your tribe at a size you choose, or send a few families off to start a village of their own. Nobody has to be harmed.",
      "Easter eggs are hidden around the game. Each one counts in \"Secrets found\" (in Advancements). A hint to start: name your people after someone on the team.",
      "Music and sound! Each era has its own music (a flute and hand drums in the Stone Age, a lyre in the Ancient era, a lute in the Medieval...), calmer at night and tense during raids. Wind, waves, birds and crickets, and sounds for building, discoveries, new eras, raids, battles and events. Click once to start it (browsers need that); the speaker in the top bar turns it off, and Menu > Sound sets the volumes.",
      "A cinematic world: the sun rises and sets (a day lasts about 3 minutes), with golden mornings, sunsets, moonlit nights and stars. Fires light up the dark, the sea has rolling waves that catch the sun, and clouds drift over the islands, their shadows sliding across the land.",
      "A new game opens with a camera fly-in over the islands, and each new era with a slow turn round your village and its name. Click to skip.",
      "Menu > Graphics: Fancy adds a film look (soft shading, glowing fires, a colour grade for each era); Fast is smoother on phones. Turn off Day and night to keep it always day.",
      "A much shorter tutorial: five steps, one line each (\"Tell me more\" if you want the why). The rest you learn by playing. Played before? Press \"I've played before\" on the title screen to skip it.",
      "Every meter now explains itself: click Food, Shelter, Happiness, Literacy, Energy or Sustainability to see each thing pushing it up or down, and press \"What should I fix?\" for the three changes that would raise it most.",
      "Hunters are now your own people: someone from a gatherer's camp (or someone free) walks out, hunts, and walks back to where they set out. Nobody appears out of, or disappears into, the fire any more.",
      "Click the Sustainability meter, then \"What should I fix?\": it lists the three things costing the land the most, and exactly what to do about each.",
      "Fishing Spots can now go on the river bank as well as on beaches. Watch Fires can only go on beaches, where the lookouts can see boats coming.",
      "Canoes! After Rafts & Fishing, build a Canoe Dock on the beach. The first canoe finds the Southern Isles, where you can then build farms, fishing, woodcutters, pens and gatherers; later canoes fish the open sea. Every canoe is cut from one big tree, and buildings on small islands cost Sustainability.",
      "Rebellions, from the Medieval era: if happiness stays under 30, unrest brews, and 90 seconds later some of your people take up arms. Crush them with your warriors (people die, and happiness drops), meet their demands (coins and food), or cheer the town up before they rise. Left alone, they sack the stores and leave.",
      "Scouting takes time now: the scouts set out (a marker shows where), and the new land is mapped when they come back about 18 seconds later. The Scout button counts down meanwhile.",
      "Removed the 'Deer at the forest edge' moment: it was hard to see and did little.",
      "Someone you drop on a Woodcutter to help now walks out to a tree it is felling and chops at the trunk, instead of swinging at the air. With no trees left, they split logs at the chopping block.",
      "No more rain moment. Instead, when the land is well watered, a field's wheat visibly shoots up (+2 food for each field). The birds coming back now circle over the forest itself, just above the trees, not over the grass beside it.",
      "The year in the top bar now counts up smoothly instead of jumping every tick, and holds still while the game is paused. In later eras it no longer stops 100 years before the next era: it slows down and keeps going until the year before.",
      "People with no roof over their heads now suffer for it: −2 happiness each (up to −15), and they fall sick much more often. The warning and the Happiness tip say so.",
      "With Advancements open, Elder Ama's box no longer covers the Research button: she sits just above the bottom bar, or under the header if what she points at is down there.",
      "The Watch Fire now comes with Firekeeping (keeping a fire alive) instead of Hunting Spears.",
      "The project page is now plain HTML and CSS, so the whole team can read and edit it. It looks the same, except that its pictures are no longer squashed and its footer can be read in dark mode.",
      "Dropping someone into a fire or the sea now really hurts: the tribe grieves, −35 happiness for each death (fading over 3 minutes), even when everyone was happy. Two in a row can make your people leave. Before, the loss hardly showed.",
      "The Medieval & Renaissance era! After the great drought, choose a landmark (Great Library, Cathedral or Grand Harbour) and build it in three stages to enter the Middle Ages.",
      "Two kingdoms across the sea, the Silk Steppe and the Eastern Reach, each with a mood toward you. Send gifts, sign treaties, or raid them (they will come for revenge). Their ships and armies sail in their own colours.",
      "Ships: explore new islands for outposts (each overseas building costs coins to keep supplied), meet the kingdoms and trade.",
      "The era ends with the Black Death. Close the harbour, learn Quarantine, build latrines and healers: the more ready the town, the fewer it takes. How deadly it is depends on the difficulty.",
      "New buildings: Castle, Windmill, Guild Hall, University, Shipyard, Trading Post, and the three landmarks, plus 12 new discovery scenes.",
      "Agriculture now costs 30 Knowledge instead of 80. In return it asks for two more things first: 2 Wooden Houses and an Elder's Hut (as well as 3 Farmland, 12 people and 50 food stored).",
      "During the tutorial you can now turn the camera (right-drag, or two fingers) and zoom (mouse wheel). The highlighted spot follows along.",
      "People helping at farms now hold the hoe in both hands, lift it overhead and bring it down into the soil (an axe at the woodcutter, a pick at the quarry). Warriors hold their club, spear (now with a stone point) or sword in the hand, ready.",
      "Rain on the fields: the cloud now drifts in from the side, and the rain starts once it is over the field.",
      "The protected old grove is marked with red cloth tied round its trees, instead of grey posts.",
      "Hard mode: a building's panel now says what wear does (below 50% it makes less, at 0% it stops) and that repairing puts it back to 100%.",
      "Removed the 'A tree blew down' moment.",
      "The old grove's second choice now says plainly that you lose the grove.",
      "Feedback has a spam guard: very short messages, link spam, repeats and sending too often are refused with a short reason.",
      "Fixed: the Close button on the Advancements screen could not be clicked (the top bar was covering it).",
      "Clicking a campfire no longer picks up the people sitting round it by accident, and dropping someone into a fire or the open sea now takes a second click to confirm.",
      "Fire keepers: every campfire now has someone who adds wood when it burns out (1 wood each time, like relighting), so you no longer have to keep clicking. Click a fire to send its keeper away and save wood. Keepers can't relight in a storm.",
      "If people are left without a roof, a warning says so, and what was lost (a house burned by raiders or sparks, wrecked by a storm, or broken down).",
      "Clicking where you can't plant or build now tells you why, instead of doing nothing.",
      "Short of Knowledge for Agriculture? The goal line now points you to Storytelling and Elder's Huts, which teach every day.",
      "During the tutorial and Elder Ama's guided steps, the speed buttons and the Menu still work, and her instructions are no longer dimmed.",
      "Discovery scenes now show what their words say: Storytelling has people sitting round a fire, Writing a clay tablet, Spears a spear, Cave Paintings happen in a cave by torchlight, The Wheel a cart, and so on, with things appearing on the line that mentions them.",
    ],
  },
  {
    date: "2026-09-30",
    items: [
      "Hover (or tap) the population or warriors counter at the top: those people light up in yellow on the map, and it tells you how many people each figure stands for.",
      "Click the Knowledge counter (the bulb at the top) to see how to get more: the firsts still waiting for you and what teaches every day. A +N pops up whenever you learn something.",
      "Someone you drop on a field or workplace now gets to work there instead of sitting down: a hoe in the fields, an axe at the woodcutter, a pick at the quarry, moving from patch to patch.",
      "Skipping the tutorial now gives you everything it would have: Early Farming, a Farmland and a Wooden House as well.",
      "Small moments now happen on the map: deer run past, a tree blows down, birds circle the forest, rain falls on the fields, with a label over the spot.",
      "Selective logging now really gives half the wood of clear-cutting. It used to drop to a fifth or less once the trees had been thinned. If no tree is big enough to thin yet, the woodcutter waits for them to grow and its panel says so.",
      "Picking people up is easier: click near someone (you no longer have to hit them exactly) and they stay in your hand; click again or press Enter to put them down. Move them with the arrow keys (or WASD), press Esc to put them back, or press P to pick up whoever is nearest the middle of the screen.",
      "Hard mode: buildings wear out. Worn buildings make less and a hammer appears over them; broken ones make nothing and a broken home holds only half its people. Click a building to repair it for a small part of its cost.",
      "Natural disasters, with a warning before each one. Storms blow out every fire and can wreck wooden buildings (forest around them breaks the wind). Floods cover the land by the river and the sea and stop the buildings there, then leave rich silt that makes those fields grow more. Earthquakes shake the camera, crack the ground and bring down buildings, brick and stone more than wood. Landslides only happen where the trees on a hillside were cut or the hill was quarried.",
      "Discovery scenes: every time you research an advancement or find a secret, a short pixel scene shows the moment your people worked it out. Click to speed it up, or skip it.",
      "New era: the Classical era! Beat the Roman legion, learn Coinage (new) and grow to 40 people to enter it.",
      "Beating the legion no longer ends the story. After it, you have 20 minutes (15 on Hard) to reach the Classical era before the world moves on.",
      "A river now runs from the hills south of the village down to the sea.",
      "Ten new Classical advancements and eight new buildings: Well, Aqueduct, Watermill, Town House, Public Latrines, Bathhouse, Market and Academy. Each has its own trade-off.",
      "Town Houses hold 24 people and keep them warm without a campfire, but packed towns spread sickness unless there are latrines.",
      "Trade: build a Market, learn Silk Road Contact and send caravans across the sea to the Silk Steppe for silver and new ideas. Sickness travels the same roads.",
      "Paved Roads turn the worn paths into stone roads and bring 25% more coins. Iron Weapons make warriors fight three times as hard.",
      "The Classical era ends with a great drought. The elders warn you 3 minutes ahead; then for 3 minutes the rain almost stops. Wells, aqueducts, full granaries and standing forests get you through. Come through it and your story is complete.",
      "A town only grows when it makes at least as much food as it eats (stored food alone no longer lets it grow into a famine), and never by more than about one person every 4 seconds.",
      "In a famine, the people you can't feed at all leave to look for food elsewhere, so a big town shrinks instead of starving to the last person.",
      "Worn-out land now hurts a little just under Sustainability 40 and more the lower it falls (it used to cut harvests by 40% straight away). The warning names what is costing the land the most.",
      "The game now saves right after anything you do, not just every few seconds.",
      "In a game, the accessibility settings (dark mode, font, high contrast, larger text) are now in the Menu, so the Settings button no longer covers the Advancements button.",
    ],
  },
  {
    date: "2026-09-29",
    items: [
      "Building next to the clouds no longer uncovers new land. Send scouts to explore.",
      "Planting saplings now comes with Early Farming (the Plant button appears once you've learned it).",
      "Growing your tribe teaches less: +1 Knowledge once, when you first reach 10 people (was +5 at 10, 15, 20, 30 and 50).",
      "No fire, no cooking: without a lit campfire your people eat their food raw and need 30% more of it.",
      "Grass fires from campfire sparks are about three times rarer, and you now get a clear message when one happens.",
      "Don't fall behind: reach the Ancient era within 45 minutes (30 on Hard, 60 on Easy) or the world moves on without you. A warning counts down the last 5 minutes.",
      "The Stone Age calendar no longer gets stuck at 3,100 BCE: it keeps moving all game and reaches 3,000 BCE just as the world moves on.",
      "Hunters no longer vanish on the way home from a far-off hunt.",
      "Pick people up! Grab a villager and drop them somewhere. Drop them at a building and they help out, at a cold fire and they relight it. But the fire, the sea, the mountains and the unknown are dangerous.",
      "Chief level: an XP bar in the top bar that fills as you build, grow, research, win raids, plant trees and keep everyone fed. Each level gives a title and a little Knowledge.",
      "A goal line under the top bar always says what to aim for next, with your progress.",
      "New games open with a short story: who your people are, your goal, and how you can lose.",
      "New: First-time mode, picked for you on your first game. The clock starts at half speed, raids and events come less often, raiders are weaker, and famine takes longer. After a while it runs at normal pace.",
      "Raiders march smoothly at every speed (at 4x they used to lurch and stutter).",
      "Online (optional): send the team feedback from the Menu, save your game to the cloud and continue it anywhere with a code, and post a finished game to the leaderboard.",
      "Raids are yours to answer: when raiders land, choose to fight (watch the battle and train warriors to tip it), hide in the houses (nobody dies, they take less) or pay tribute (they leave, but come back sooner).",
      "Three kinds of raiders: small bands after your wood, war parties after food and wood, and fire raids that burn a building.",
      "War Camps now hold 6 warriors each, and the Train button tells you when to build another camp.",
      "New: the Watch Fire (after Hunting Spears). Built on the shore, it spots raiders sooner and adds a little defense, but burns wood.",
      "Warriors patrol around their camps and watch fires, and new recruits march out of the War Camp.",
      "More happens: small moments every 30-60 seconds (a deer herd passes, a baby is born, wind blows out a fire, mice get into the stores...), a shorter quiet start, and event cards about twice as often.",
      "Famine is hard but you can come back from it: while the stores are empty about one person dies every 10 seconds, and you have 2 minutes (on Normal) to find food. The warning offers three emergency measures, each with a price: forage the forest, slaughter a herd, or eat the seed grain.",
      "You can now lose by ruining the land: if Sustainability stays below 20 for about two minutes, the land collapses and your people must leave. A countdown warns you first, and planting, selective logging or clearing less forest brings it back.",
      "Hovering the Food & Water meter now explains it: it shows whether you make enough food for everyone (45 = just enough), not how much is stored. Stored food is the number in the top bar.",
      "Dev mode: new Sparks and Clear forest buttons to test house fires, rain and Sustainability.",
      "The tutorial teaches it too: Elder Ama tells you to leave a patch of ground between your house and the fire.",
      "Huts are now Wooden Houses (log walls, bark roof): thatch needs straw, and there's no straw before farming.",
      "Campfires throw sparks: grass next to them can scorch, and a wooden house right next to a fire can catch and burn down. Keep a tile between them; Firekeeping halves the risk. Mud-brick houses don't burn.",
      "One thing at a time: event cards, raids, Elder Ama's lessons and outbreaks out of nowhere now wait at least a minute after each other.",
      "Buildings you can't afford yet are dimmed in the build bar, like Plant, Train and Scout.",
      "The Sustainability panel only lists what is actually affecting the land (no more \"Forest standing: 100% +0\").",
      "The pointing hand now picks spots that avoid harm: quarries go well away from the village and its fields, gatherers away from fires, fields away from forest when it can.",
      "Deer and boar now walk: their legs swing and their bodies bob as they move.",
      "The old grove is marked on the map once you protect it (standing stones and a label), and nothing can be built on it.",
      "You can see the Ancient era now: villagers wear dyed linen, warriors wear leather, the light is warmer, paths wear into the ground between buildings, and the top bar gets a bronze trim.",
      "The tutorial no longer starts you on a big pile: Elder Ama hands over what each step needs as you reach it, and a small reserve (40 food, 10 wood) at the end.",
      "Storytelling and Herbalism now come after Toolmaking, because the Elder's Hut and Healer's Hut need stone from a quarry.",
      "Clearer wording: a spearman counts as 1.5 warriors in a fight; Firekeeping makes fires last 50% longer; canals make fields grow 50% more.",
      "Bronze Weapons' \"beat a raid\" goal counts any raid you have ever beaten.",
      "Farmland clears the nearest patch of forest for good, and forests bring rain: the less forest stands, the less rain falls and the less every field grows (down to half). Watch \"rain\" by your food.",
      "Skipping the tutorial no longer leaves you its whole budget: you start with 40 food and 10 wood.",
      "Rebalanced after full test games: people eat a quarter less, woodcutters and quarries were tuned, Agriculture costs 80, raids grow more slowly over time, and the Roman legion comes about 12 minutes into the Ancient era.",
      "Food and wood come in about a third slower (gatherers, farms, fishing, pens and woodcutters), so big stockpiles take real work.",
      "Every advancement now has its own goal before you can research it (e.g. Herding: hunt 3 animals; Agriculture: 3 fields, 12 people, 50 food stored). Each card shows the goal and your progress.",
      "After each advancement, Elder Ama and the pointing hand walk you through what it unlocked, like the opening tutorial.",
      "Hunting Spears lets warriors carry spears: train new spearmen or give your warriors spears (4 wood). Spearmen fight 1.5x as hard and you can see them on the map.",
      "Knowledge is harder to come by: milestones and Elder's Huts teach less, extra huts teach only half, only your first 5 scouting trips teach anything, and Agriculture costs 100. Reaching the Ancient era now takes real time, and the Ancient era runs slower so there is time to prepare for the Romans.",
      "Quarries really cut the hill away now: the tile sinks and turns to bare rock, a mountain loses its peak, and the scar (and its Sustainability cost) stays after the quarry is gone.",
      "The raid banner shows where your defense comes from (warriors, spears, war camp, walls).",
      "Mountains now rise in the outer highlands of each island instead of right next to your village.",
      "Hover over a hut or house to see how many people live there.",
      "Skipping the tutorial now also gives you a War Camp and one warrior, like the tutorial would, so the first raiders don't walk right in.",
      "Knowledge now comes from milestones: your first of each building, reaching 10, 15, 20, 30 and 50 people, each scouting trip (+1, or +2 if it maps a lot of land), beating raiders and planting saplings. Elder's Huts and schools still teach a little all the time.",
      "Dev mode: pick any event card or elder lesson from a list and trigger it.",
      "Elder Ama tells you when you have learned enough to research something new, and the Advancements button shows how many you can afford.",
      "Elder Ama now explains the tree stumps on each building: how hard it is on the land, and where to look.",
      "A lit campfire right next to a gatherer's camp scares off the animals: that camp makes 30% less food. Keep fires and camps a tile apart.",
      "\"The herds are thinning\": letting the herds recover now costs food today, as holding back really would.",
      "Warriors and villagers no longer pace back and forth beside buildings: they walk to the near side and pause when their path is blocked.",
      "The campfire warning now says cold people become unhappy.",
      "Gatherer camps are no longer free to spam: the wild only has so much, so each extra camp adds just 25% of a camp's food, and every camp past the second hunts animals faster than they breed (−2 Sustainability each). Elder Ama explains why.",
      "Losing (famine, unrest or conquest) is never called the best ending any more, however healthy the land is.",
      "Elder Ama's tutorial now reads like one conversation, explains how Knowledge is earned, and says goodbye when you're ready.",
      "Stone quarries throw up dust: gatherers, farms and pens within 2 tiles make 40% less food.",
      "Panels no longer draw over each other, and the building card stays bright during the tutorial.",
      "Countdowns tick down every second instead of jumping.",
      "The Advancements panel shows how fast you earn Knowledge.",
      "Hide Clothing is now called Warm Clothes.",
      "The building card sits beside the tile, so you can see where you're placing.",
      "An Updates bar at the top of the pages lists what's new.",
      "Villagers sit on the logs around the campfire, the war camp no longer has a stray fire, and the book icon looks like a book.",
    ],
  },
];
