// What's new, newest first. Shown at the top of the landing page and the title
// screen. Add a line here for every change a player would notice.
export interface Update {
  date: string; // YYYY-MM-DD
  items: string[];
}

export const UPDATES: Update[] = [
  {
    date: "2026-10-01",
    items: [
      "Hunters are now your own people: someone from a gatherer's camp (or someone free) walks out, hunts, and walks back to where they set out. Nobody appears out of, or disappears into, the fire any more.",
      "Click the Sustainability meter, then \"What should I fix?\": it lists the three things costing the land the most, and exactly what to do about each.",
      "Fishing Spots can now go on the river bank as well as on beaches. Watch Fires can only go on beaches, where the lookouts can see boats coming.",
      "Canoes! After Rafts & Fishing, build a Canoe Dock on the beach. The first canoe finds the Southern Isles, where you can then build farms, fishing, woodcutters, pens and gatherers; later canoes fish the open sea. Every canoe is cut from one big tree, and buildings on small islands cost Sustainability.",
      "Rebellions, from the Medieval era: if happiness stays under 30, unrest brews, and 90 seconds later some of your people take up arms. Crush them with your warriors (people die, and happiness drops), meet their demands (coins and food), or cheer the town up before they rise. Left alone, they sack the stores and leave.",
      "Scouting takes time now: the scouts set out (a marker shows where), and the new land is mapped when they come back about 18 seconds later. The Scout button counts down meanwhile.",
      "Removed the 'Deer at the forest edge' moment: it was hard to see and did little.",
      "Someone you drop on a Woodcutter to help now walks out to a tree it is felling and chops at the trunk, instead of swinging at the air. With no trees left, they split logs at the chopping block.",
      "No more rain moment. Instead, when the land is well watered, a field's wheat visibly shoots up (+2 food for each field). The birds coming back now circle over the forest itself, just above the trees, not over the grass beside it.",
      "The year in the top bar now counts up smoothly instead of jumping every tick, and holds still while the game is paused. In later eras it no longer stops 100 years before the next era: it slows down and keeps going until the year before.",
      "People with no roof over their heads now suffer for it: −2 happiness each (up to −15), and they fall sick much more often. The warning and the Happiness tip say so.",
      "With Advancements open, Elder Ama's box no longer covers the Research button: she sits just above the bottom bar, or under the header if what she points at is down there.",
      "The Watch Fire now comes with Firekeeping (keeping a fire alive) instead of Hunting Spears.",
      "The project page is now plain HTML and CSS, so the whole team can read and edit it. It looks the same, except that its pictures are no longer squashed and its footer can be read in dark mode.",
      "Dropping someone into a fire or the sea now really hurts: the tribe grieves, −35 happiness for each death (fading over 3 minutes), even when everyone was happy. Two in a row can make your people leave. Before, the loss hardly showed.",
      "The Medieval & Renaissance era! After the great drought, choose a landmark (Great Library, Cathedral or Grand Harbour) and build it in three stages to enter the Middle Ages.",
      "Two kingdoms across the sea, the Silk Steppe and the Eastern Reach, each with a mood toward you. Send gifts, sign treaties, or raid them (they will come for revenge). Their ships and armies sail in their own colours.",
      "Ships: explore new islands for outposts (each overseas building costs coins to keep supplied), meet the kingdoms and trade.",
      "The era ends with the Black Death. Close the harbour, learn Quarantine, build latrines and healers: the more ready the town, the fewer it takes. How deadly it is depends on the difficulty.",
      "New buildings: Castle, Windmill, Guild Hall, University, Shipyard, Trading Post, and the three landmarks, plus 12 new discovery scenes.",
      "Agriculture now costs 30 Knowledge instead of 80. In return it asks for two more things first: 2 Wooden Houses and an Elder's Hut (as well as 3 Farmland, 12 people and 50 food stored).",
      "During the tutorial you can now turn the camera (right-drag, or two fingers) and zoom (mouse wheel). The highlighted spot follows along.",
      "People helping at farms now hold the hoe in both hands, lift it overhead and bring it down into the soil (an axe at the woodcutter, a pick at the quarry). Warriors hold their club, spear (now with a stone point) or sword in the hand, ready.",
      "Rain on the fields: the cloud now drifts in from the side, and the rain starts once it is over the field.",
      "The protected old grove is marked with red cloth tied round its trees, instead of grey posts.",
      "Hard mode: a building's panel now says what wear does (below 50% it makes less, at 0% it stops) and that repairing puts it back to 100%.",
      "Removed the 'A tree blew down' moment.",
      "The old grove's second choice now says plainly that you lose the grove.",
      "Feedback has a spam guard: very short messages, link spam, repeats and sending too often are refused with a short reason.",
      "Fixed: the Close button on the Advancements screen could not be clicked (the top bar was covering it).",
      "Clicking a campfire no longer picks up the people sitting round it by accident, and dropping someone into a fire or the open sea now takes a second click to confirm.",
      "Fire keepers: every campfire now has someone who adds wood when it burns out (1 wood each time, like relighting), so you no longer have to keep clicking. Click a fire to send its keeper away and save wood. Keepers can't relight in a storm.",
      "If people are left without a roof, a warning says so, and what was lost (a house burned by raiders or sparks, wrecked by a storm, or broken down).",
      "Clicking where you can't plant or build now tells you why, instead of doing nothing.",
      "Short of Knowledge for Agriculture? The goal line now points you to Storytelling and Elder's Huts, which teach every day.",
      "During the tutorial and Elder Ama's guided steps, the speed buttons and the Menu still work, and her instructions are no longer dimmed.",
      "Discovery scenes now show what their words say: Storytelling has people sitting round a fire, Writing a clay tablet, Spears a spear, Cave Paintings happen in a cave by torchlight, The Wheel a cart, and so on, with things appearing on the line that mentions them.",
    ],
  },
  {
    date: "2026-09-30",
    items: [
      "Hover (or tap) the population or warriors counter at the top: those people light up in yellow on the map, and it tells you how many people each figure stands for.",
      "Click the Knowledge counter (the bulb at the top) to see how to get more: the firsts still waiting for you and what teaches every day. A +N pops up whenever you learn something.",
      "Someone you drop on a field or workplace now gets to work there instead of sitting down: a hoe in the fields, an axe at the woodcutter, a pick at the quarry, moving from patch to patch.",
      "Skipping the tutorial now gives you everything it would have: Early Farming, a Farmland and a Wooden House as well.",
      "Small moments now happen on the map: deer run past, a tree blows down, birds circle the forest, rain falls on the fields, with a label over the spot.",
      "Selective logging now really gives half the wood of clear-cutting. It used to drop to a fifth or less once the trees had been thinned. If no tree is big enough to thin yet, the woodcutter waits for them to grow and its panel says so.",
      "Picking people up is easier: click near someone (you no longer have to hit them exactly) and they stay in your hand; click again or press Enter to put them down. Move them with the arrow keys (or WASD), press Esc to put them back, or press P to pick up whoever is nearest the middle of the screen.",
      "Hard mode: buildings wear out. Worn buildings make less and a hammer appears over them; broken ones make nothing and a broken home holds only half its people. Click a building to repair it for a small part of its cost.",
      "Natural disasters, with a warning before each one. Storms blow out every fire and can wreck wooden buildings (forest around them breaks the wind). Floods cover the land by the river and the sea and stop the buildings there, then leave rich silt that makes those fields grow more. Earthquakes shake the camera, crack the ground and bring down buildings, brick and stone more than wood. Landslides only happen where the trees on a hillside were cut or the hill was quarried.",
      "Discovery scenes: every time you research an advancement or find a secret, a short pixel scene shows the moment your people worked it out. Click to speed it up, or skip it.",
      "New era: the Classical era! Beat the Roman legion, learn Coinage (new) and grow to 40 people to enter it.",
      "Beating the legion no longer ends the story. After it, you have 20 minutes (15 on Hard) to reach the Classical era before the world moves on.",
      "A river now runs from the hills south of the village down to the sea.",
      "Ten new Classical advancements and eight new buildings: Well, Aqueduct, Watermill, Town House, Public Latrines, Bathhouse, Market and Academy. Each has its own trade-off.",
      "Town Houses hold 24 people and keep them warm without a campfire, but packed towns spread sickness unless there are latrines.",
      "Trade: build a Market, learn Silk Road Contact and send caravans across the sea to the Silk Steppe for silver and new ideas. Sickness travels the same roads.",
      "Paved Roads turn the worn paths into stone roads and bring 25% more coins. Iron Weapons make warriors fight three times as hard.",
      "The Classical era ends with a great drought. The elders warn you 3 minutes ahead; then for 3 minutes the rain almost stops. Wells, aqueducts, full granaries and standing forests get you through. Come through it and your story is complete.",
      "A town only grows when it makes at least as much food as it eats (stored food alone no longer lets it grow into a famine), and never by more than about one person every 4 seconds.",
      "In a famine, the people you can't feed at all leave to look for food elsewhere, so a big town shrinks instead of starving to the last person.",
      "Worn-out land now hurts a little just under Sustainability 40 and more the lower it falls (it used to cut harvests by 40% straight away). The warning names what is costing the land the most.",
      "The game now saves right after anything you do, not just every few seconds.",
      "In a game, the accessibility settings (dark mode, font, high contrast, larger text) are now in the Menu, so the Settings button no longer covers the Advancements button.",
    ],
  },
  {
    date: "2026-09-29",
    items: [
      "Building next to the clouds no longer uncovers new land. Send scouts to explore.",
      "Planting saplings now comes with Early Farming (the Plant button appears once you've learned it).",
      "Growing your tribe teaches less: +1 Knowledge once, when you first reach 10 people (was +5 at 10, 15, 20, 30 and 50).",
      "No fire, no cooking: without a lit campfire your people eat their food raw and need 30% more of it.",
      "Grass fires from campfire sparks are about three times rarer, and you now get a clear message when one happens.",
      "Don't fall behind: reach the Ancient era within 45 minutes (30 on Hard, 60 on Easy) or the world moves on without you. A warning counts down the last 5 minutes.",
      "The Stone Age calendar no longer gets stuck at 3,100 BCE: it keeps moving all game and reaches 3,000 BCE just as the world moves on.",
      "Hunters no longer vanish on the way home from a far-off hunt.",
      "Pick people up! Grab a villager and drop them somewhere. Drop them at a building and they help out, at a cold fire and they relight it. But the fire, the sea, the mountains and the unknown are dangerous.",
      "Chief level: an XP bar in the top bar that fills as you build, grow, research, win raids, plant trees and keep everyone fed. Each level gives a title and a little Knowledge.",
      "A goal line under the top bar always says what to aim for next, with your progress.",
      "New games open with a short story: who your people are, your goal, and how you can lose.",
      "New: First-time mode, picked for you on your first game. The clock starts at half speed, raids and events come less often, raiders are weaker, and famine takes longer. After a while it runs at normal pace.",
      "Raiders march smoothly at every speed (at 4x they used to lurch and stutter).",
      "Online (optional): send the team feedback from the Menu, save your game to the cloud and continue it anywhere with a code, and post a finished game to the leaderboard.",
      "Raids are yours to answer: when raiders land, choose to fight (watch the battle and train warriors to tip it), hide in the houses (nobody dies, they take less) or pay tribute (they leave, but come back sooner).",
      "Three kinds of raiders: small bands after your wood, war parties after food and wood, and fire raids that burn a building.",
      "War Camps now hold 6 warriors each, and the Train button tells you when to build another camp.",
      "New: the Watch Fire (after Hunting Spears). Built on the shore, it spots raiders sooner and adds a little defense, but burns wood.",
      "Warriors patrol around their camps and watch fires, and new recruits march out of the War Camp.",
      "More happens: small moments every 30-60 seconds (a deer herd passes, a baby is born, wind blows out a fire, mice get into the stores...), a shorter quiet start, and event cards about twice as often.",
      "Famine is hard but you can come back from it: while the stores are empty about one person dies every 10 seconds, and you have 2 minutes (on Normal) to find food. The warning offers three emergency measures, each with a price: forage the forest, slaughter a herd, or eat the seed grain.",
      "You can now lose by ruining the land: if Sustainability stays below 20 for about two minutes, the land collapses and your people must leave. A countdown warns you first, and planting, selective logging or clearing less forest brings it back.",
      "Hovering the Food & Water meter now explains it: it shows whether you make enough food for everyone (45 = just enough), not how much is stored. Stored food is the number in the top bar.",
      "Dev mode: new Sparks and Clear forest buttons to test house fires, rain and Sustainability.",
      "The tutorial teaches it too: Elder Ama tells you to leave a patch of ground between your house and the fire.",
      "Huts are now Wooden Houses (log walls, bark roof): thatch needs straw, and there's no straw before farming.",
      "Campfires throw sparks: grass next to them can scorch, and a wooden house right next to a fire can catch and burn down. Keep a tile between them; Firekeeping halves the risk. Mud-brick houses don't burn.",
      "One thing at a time: event cards, raids, Elder Ama's lessons and outbreaks out of nowhere now wait at least a minute after each other.",
      "Buildings you can't afford yet are dimmed in the build bar, like Plant, Train and Scout.",
      "The Sustainability panel only lists what is actually affecting the land (no more \"Forest standing: 100% +0\").",
      "The pointing hand now picks spots that avoid harm: quarries go well away from the village and its fields, gatherers away from fires, fields away from forest when it can.",
      "Deer and boar now walk: their legs swing and their bodies bob as they move.",
      "The old grove is marked on the map once you protect it (standing stones and a label), and nothing can be built on it.",
      "You can see the Ancient era now: villagers wear dyed linen, warriors wear leather, the light is warmer, paths wear into the ground between buildings, and the top bar gets a bronze trim.",
      "The tutorial no longer starts you on a big pile: Elder Ama hands over what each step needs as you reach it, and a small reserve (40 food, 10 wood) at the end.",
      "Storytelling and Herbalism now come after Toolmaking, because the Elder's Hut and Healer's Hut need stone from a quarry.",
      "Clearer wording: a spearman counts as 1.5 warriors in a fight; Firekeeping makes fires last 50% longer; canals make fields grow 50% more.",
      "Bronze Weapons' \"beat a raid\" goal counts any raid you have ever beaten.",
      "Farmland clears the nearest patch of forest for good, and forests bring rain: the less forest stands, the less rain falls and the less every field grows (down to half). Watch \"rain\" by your food.",
      "Skipping the tutorial no longer leaves you its whole budget: you start with 40 food and 10 wood.",
      "Rebalanced after full test games: people eat a quarter less, woodcutters and quarries were tuned, Agriculture costs 80, raids grow more slowly over time, and the Roman legion comes about 12 minutes into the Ancient era.",
      "Food and wood come in about a third slower (gatherers, farms, fishing, pens and woodcutters), so big stockpiles take real work.",
      "Every advancement now has its own goal before you can research it (e.g. Herding: hunt 3 animals; Agriculture: 3 fields, 12 people, 50 food stored). Each card shows the goal and your progress.",
      "After each advancement, Elder Ama and the pointing hand walk you through what it unlocked, like the opening tutorial.",
      "Hunting Spears lets warriors carry spears: train new spearmen or give your warriors spears (4 wood). Spearmen fight 1.5x as hard and you can see them on the map.",
      "Knowledge is harder to come by: milestones and Elder's Huts teach less, extra huts teach only half, only your first 5 scouting trips teach anything, and Agriculture costs 100. Reaching the Ancient era now takes real time, and the Ancient era runs slower so there is time to prepare for the Romans.",
      "Quarries really cut the hill away now: the tile sinks and turns to bare rock, a mountain loses its peak, and the scar (and its Sustainability cost) stays after the quarry is gone.",
      "The raid banner shows where your defense comes from (warriors, spears, war camp, walls).",
      "Mountains now rise in the outer highlands of each island instead of right next to your village.",
      "Hover over a hut or house to see how many people live there.",
      "Skipping the tutorial now also gives you a War Camp and one warrior, like the tutorial would, so the first raiders don't walk right in.",
      "Knowledge now comes from milestones: your first of each building, reaching 10, 15, 20, 30 and 50 people, each scouting trip (+1, or +2 if it maps a lot of land), beating raiders and planting saplings. Elder's Huts and schools still teach a little all the time.",
      "Dev mode: pick any event card or elder lesson from a list and trigger it.",
      "Elder Ama tells you when you have learned enough to research something new, and the Advancements button shows how many you can afford.",
      "Elder Ama now explains the tree stumps on each building: how hard it is on the land, and where to look.",
      "A lit campfire right next to a gatherer's camp scares off the animals: that camp makes 30% less food. Keep fires and camps a tile apart.",
      "\"The herds are thinning\": letting the herds recover now costs food today, as holding back really would.",
      "Warriors and villagers no longer pace back and forth beside buildings: they walk to the near side and pause when their path is blocked.",
      "The campfire warning now says cold people become unhappy.",
      "Gatherer camps are no longer free to spam: the wild only has so much, so each extra camp adds just 25% of a camp's food, and every camp past the second hunts animals faster than they breed (−2 Sustainability each). Elder Ama explains why.",
      "Losing (famine, unrest or conquest) is never called the best ending any more, however healthy the land is.",
      "Elder Ama's tutorial now reads like one conversation, explains how Knowledge is earned, and says goodbye when you're ready.",
      "Stone quarries throw up dust: gatherers, farms and pens within 2 tiles make 40% less food.",
      "Panels no longer draw over each other, and the building card stays bright during the tutorial.",
      "Countdowns tick down every second instead of jumping.",
      "The Advancements panel shows how fast you earn Knowledge.",
      "Hide Clothing is now called Warm Clothes.",
      "The building card sits beside the tile, so you can see where you're placing.",
      "An Updates bar at the top of the pages lists what's new.",
      "Villagers sit on the logs around the campfire, the war camp no longer has a stray fire, and the book icon looks like a book.",
    ],
  },
];
