// What's new, newest first. Shown at the top of the landing page and the title
// screen. Add a line here for every change a player would notice.
export interface Update {
  date: string; // YYYY-MM-DD
  items: string[];
}

export const UPDATES: Update[] = [
  {
    date: "2026-09-29",
    items: [
      "Hunters no longer vanish on the way home from a far-off hunt.",
      "Dev mode: new Sparks and Clear forest buttons to test house fires, rain and Sustainability.",
      "The tutorial teaches it too: Elder Ama tells you to leave a patch of ground between your house and the fire.",
      "Huts are now Wooden Houses (log walls, bark roof): thatch needs straw, and there's no straw before farming.",
      "Campfires throw sparks: grass next to them can scorch, and a wooden house right next to a fire can catch and burn down. Keep a tile between them; Firekeeping halves the risk. Mud-brick houses don't burn.",
      "One thing at a time: event cards, raids, Elder Ama's lessons and outbreaks out of nowhere now wait at least a minute after each other.",
      "Buildings you can't afford yet are dimmed in the build bar, like Plant, Train and Scout.",
      "The Sustainability panel only lists what is actually affecting the land (no more \"Forest standing: 100% +0\").",
      "The pointing hand now picks spots that avoid harm: quarries go well away from the village and its fields, gatherers away from fires, fields away from forest when it can.",
      "Deer and boar now walk: their legs swing and their bodies bob as they move.",
      "The old grove is marked on the map once you protect it (standing stones and a label), and nothing can be built on it.",
      "You can see the Ancient era now: villagers wear dyed linen, warriors wear leather, the light is warmer, paths wear into the ground between buildings, and the top bar gets a bronze trim.",
      "The tutorial no longer starts you on a big pile: Elder Ama hands over what each step needs as you reach it, and a small reserve (40 food, 10 wood) at the end.",
      "Storytelling and Herbalism now come after Toolmaking, because the Elder's Hut and Healer's Hut need stone from a quarry.",
      "Clearer wording: a spearman counts as 1.5 warriors in a fight; Firekeeping makes fires last 50% longer; canals make fields grow 50% more.",
      "Bronze Weapons' \"beat a raid\" goal counts any raid you have ever beaten.",
      "Farmland clears the nearest patch of forest for good, and forests bring rain: the less forest stands, the less rain falls and the less every field grows (down to half). Watch \"rain\" by your food.",
      "Skipping the tutorial no longer leaves you its whole budget: you start with 40 food and 10 wood.",
      "Rebalanced after full test games: people eat a quarter less, woodcutters and quarries were tuned, Agriculture costs 80, raids grow more slowly over time, and the Roman legion comes about 12 minutes into the Ancient era.",
      "Food and wood come in about a third slower (gatherers, farms, fishing, pens and woodcutters), so big stockpiles take real work.",
      "Every advancement now has its own goal before you can research it (e.g. Herding: hunt 3 animals; Agriculture: 3 fields, 12 people, 50 food stored). Each card shows the goal and your progress.",
      "After each advancement, Elder Ama and the pointing hand walk you through what it unlocked, like the opening tutorial.",
      "Hunting Spears lets warriors carry spears: train new spearmen or give your warriors spears (4 wood). Spearmen fight 1.5x as hard and you can see them on the map.",
      "Knowledge is harder to come by: milestones and Elder's Huts teach less, extra huts teach only half, only your first 5 scouting trips teach anything, and Agriculture costs 100. Reaching the Ancient era now takes real time, and the Ancient era runs slower so there is time to prepare for the Romans.",
      "Quarries really cut the hill away now: the tile sinks and turns to bare rock, a mountain loses its peak, and the scar (and its Sustainability cost) stays after the quarry is gone.",
      "The raid banner shows where your defense comes from (warriors, spears, war camp, walls).",
      "Mountains now rise in the outer highlands of each island instead of right next to your village.",
      "Hover over a hut or house to see how many people live there.",
      "Skipping the tutorial now also gives you a War Camp and one warrior, like the tutorial would, so the first raiders don't walk right in.",
      "Knowledge now comes from milestones: your first of each building, reaching 10, 15, 20, 30 and 50 people, each scouting trip (+1, or +2 if it maps a lot of land), beating raiders and planting saplings. Elder's Huts and schools still teach a little all the time.",
      "Dev mode: pick any event card or elder lesson from a list and trigger it.",
      "Elder Ama tells you when you have learned enough to research something new, and the Advancements button shows how many you can afford.",
      "Elder Ama now explains the tree stumps on each building: how hard it is on the land, and where to look.",
      "A lit campfire right next to a gatherer's camp scares off the animals: that camp makes 30% less food. Keep fires and camps a tile apart.",
      "\"The herds are thinning\": letting the herds recover now costs food today, as holding back really would.",
      "Warriors and villagers no longer pace back and forth beside buildings: they walk to the near side and pause when their path is blocked.",
      "The campfire warning now says cold people become unhappy.",
      "Gatherer camps are no longer free to spam: the wild only has so much, so each extra camp adds just 25% of a camp's food, and every camp past the second hunts animals faster than they breed (−2 Sustainability each). Elder Ama explains why.",
      "Losing (famine, unrest or conquest) is never called the best ending any more, however healthy the land is.",
      "Elder Ama's tutorial now reads like one conversation, explains how Knowledge is earned, and says goodbye when you're ready.",
      "Stone quarries throw up dust: gatherers, farms and pens within 2 tiles make 40% less food.",
      "Panels no longer draw over each other, and the building card stays bright during the tutorial.",
      "Countdowns tick down every second instead of jumping.",
      "The Advancements panel shows how fast you earn Knowledge.",
      "Hide Clothing is now called Warm Clothes.",
      "The building card sits beside the tile, so you can see where you're placing.",
      "An Updates bar at the top of the pages lists what's new.",
      "Villagers sit on the logs around the campfire, the war camp no longer has a stray fire, and the book icon looks like a book.",
    ],
  },
];
